-- Recibos avulsos de recebimento e pagamento, previstos ou efetivos.
CREATE TABLE IF NOT EXISTS recibos_avulsos (
  id CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  numero INT NOT NULL AUTO_INCREMENT UNIQUE,
  tipo ENUM('recebimento','pagamento') NOT NULL,
  status ENUM('previsto','efetivo') NOT NULL,
  data DATE NOT NULL,
  valor DECIMAL(14,2) NOT NULL,
  descricao VARCHAR(500) NOT NULL,
  irmao_id CHAR(36) NULL,
  terceiro_id CHAR(36) NULL,
  plano_conta_id CHAR(36) NOT NULL,
  conta_financeira_id CHAR(36) NULL,
  forma_pagamento VARCHAR(100) NULL,
  observacoes TEXT NULL,
  lancamento_id CHAR(36) NULL,
  conciliacao_id CHAR(36) NULL,
  criado_por CHAR(36) NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_recibo_avulso_pessoa CHECK ((irmao_id IS NOT NULL) <> (terceiro_id IS NOT NULL)),
  CONSTRAINT chk_recibo_avulso_valor CHECK (valor > 0),
  CONSTRAINT fk_ra_irmao FOREIGN KEY (irmao_id) REFERENCES irmaos(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ra_terceiro FOREIGN KEY (terceiro_id) REFERENCES terceiros(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ra_plano FOREIGN KEY (plano_conta_id) REFERENCES plano_contas(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ra_conta FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ra_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ra_conciliacao FOREIGN KEY (conciliacao_id) REFERENCES conciliacoes(id) ON DELETE RESTRICT,
  UNIQUE KEY recibo_avulso_conciliacao_uniq (conciliacao_id)
) ENGINE=InnoDB;
