/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTesourariaIndexRouteImport } from './routes/_authenticated/tesouraria/index'
import { Route as AuthenticatedSessoesIndexRouteImport } from './routes/_authenticated/sessoes/index'
import { Route as AuthenticatedIrmaosIndexRouteImport } from './routes/_authenticated/irmaos/index'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs/index'
import { Route as AuthenticatedGestoesIndexRouteImport } from './routes/_authenticated/gestoes/index'
import { Route as AuthenticatedTerceirosIndexRouteImport } from './routes/_authenticated/terceiros/index'
import { Route as AuthenticatedTesourariaContasPagarRouteImport } from './routes/_authenticated/tesouraria/contas-pagar'
import { Route as AuthenticatedTesourariaPlanoContasRouteImport } from './routes/_authenticated/tesouraria/plano-contas'
import { Route as AuthenticatedTesourariaContasRouteImport } from './routes/_authenticated/tesouraria/contas'
import { Route as AuthenticatedSessoesIdRouteImport } from './routes/_authenticated/sessoes/$id'
import { Route as AuthenticatedRelatoriosInadimplentesRouteImport } from './routes/_authenticated/relatorios/inadimplentes'
import { Route as AuthenticatedRelatoriosFrequenciaRouteImport } from './routes/_authenticated/relatorios/frequencia'
import { Route as AuthenticatedIrmaosNovoRouteImport } from './routes/_authenticated/irmaos/novo'
import { Route as AuthenticatedIrmaosIdRouteImport } from './routes/_authenticated/irmaos/$id'
import { Route as AuthenticatedContabilidadeAuditoriaRouteImport } from './routes/_authenticated/contabilidade/auditoria'
import { Route as AuthenticatedOrgsPotenciasRouteImport } from './routes/_authenticated/orgs/potencias'
import { Route as AuthenticatedGestoesCargosRouteImport } from './routes/_authenticated/gestoes/cargos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTesourariaIndexRoute =
  AuthenticatedTesourariaIndexRouteImport.update({
    id: '/tesouraria/',
    path: '/tesouraria/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIndexRoute =
  AuthenticatedSessoesIndexRouteImport.update({
    id: '/sessoes/',
    path: '/sessoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIrmaosIndexRoute =
  AuthenticatedIrmaosIndexRouteImport.update({
    id: '/irmaos/',
    path: '/irmaos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestoesIndexRoute =
  AuthenticatedGestoesIndexRouteImport.update({
    id: '/gestoes/',
    path: '/gestoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerceirosIndexRoute =
  AuthenticatedTerceirosIndexRouteImport.update({
    id: '/terceiros/',
    path: '/terceiros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaPlanoContasRoute =
  AuthenticatedTesourariaPlanoContasRouteImport.update({
    id: '/tesouraria/plano-contas',
    path: '/tesouraria/plano-contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaContasRoute =
  AuthenticatedTesourariaContasRouteImport.update({
    id: '/tesouraria/contas',
    path: '/tesouraria/contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaContasPagarRoute =
  AuthenticatedTesourariaContasPagarRouteImport.update({
    id: '/tesouraria/contas-pagar',
    path: '/tesouraria/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIdRoute = AuthenticatedSessoesIdRouteImport.update({
  id: '/sessoes/$id',
  path: '/sessoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosInadimplentesRoute =
  AuthenticatedRelatoriosInadimplentesRouteImport.update({
    id: '/relatorios/inadimplentes',
    path: '/relatorios/inadimplentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosFrequenciaRoute =
  AuthenticatedRelatoriosFrequenciaRouteImport.update({
    id: '/relatorios/frequencia',
    path: '/relatorios/frequencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIrmaosNovoRoute = AuthenticatedIrmaosNovoRouteImport.update({
  id: '/irmaos/novo',
  path: '/irmaos/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIrmaosIdRoute = AuthenticatedIrmaosIdRouteImport.update({
  id: '/irmaos/$id',
  path: '/irmaos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContabilidadeAuditoriaRoute =
  AuthenticatedContabilidadeAuditoriaRouteImport.update({
    id: '/contabilidade/auditoria',
    path: '/contabilidade/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsPotenciasRoute =
  AuthenticatedOrgsPotenciasRouteImport.update({
    id: '/orgs/potencias',
    path: '/orgs/potencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestoesCargosRoute =
  AuthenticatedGestoesCargosRouteImport.update({
    id: '/gestoes/cargos',
    path: '/gestoes/cargos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/irmaos/': typeof AuthenticatedIrmaosIndexRoute
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/gestoes/': typeof AuthenticatedGestoesIndexRoute
  '/terceiros/': typeof AuthenticatedTerceirosIndexRoute
  '/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/tesouraria/': typeof AuthenticatedTesourariaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/irmaos': typeof AuthenticatedIrmaosIndexRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/gestoes': typeof AuthenticatedGestoesIndexRoute
  '/terceiros': typeof AuthenticatedTerceirosIndexRoute
  '/sessoes': typeof AuthenticatedSessoesIndexRoute
  '/tesouraria': typeof AuthenticatedTesourariaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/_authenticated/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/_authenticated/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/_authenticated/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/_authenticated/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/_authenticated/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/_authenticated/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/_authenticated/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/_authenticated/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/_authenticated/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/_authenticated/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/_authenticated/irmaos/': typeof AuthenticatedIrmaosIndexRoute
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/gestoes/': typeof AuthenticatedGestoesIndexRoute
  '/_authenticated/terceiros/': typeof AuthenticatedTerceirosIndexRoute
  '/_authenticated/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/_authenticated/tesouraria/': typeof AuthenticatedTesourariaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/contabilidade/auditoria'
    | '/orgs/potencias'
    | '/gestoes/cargos'
    | '/irmaos/$id'
    | '/irmaos/novo'
    | '/relatorios/frequencia'
    | '/relatorios/inadimplentes'
    | '/sessoes/$id'
    | '/tesouraria/contas'
    | '/tesouraria/contas-pagar'
    | '/tesouraria/plano-contas'
    | '/irmaos/'
    | '/orgs/'
    | '/gestoes/'
    | '/terceiros/'
    | '/sessoes/'
    | '/tesouraria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/contabilidade/auditoria'
    | '/orgs/potencias'
    | '/gestoes/cargos'
    | '/irmaos/$id'
    | '/irmaos/novo'
    | '/relatorios/frequencia'
    | '/relatorios/inadimplentes'
    | '/sessoes/$id'
    | '/tesouraria/contas'
    | '/tesouraria/contas-pagar'
    | '/tesouraria/plano-contas'
    | '/irmaos'
    | '/orgs'
    | '/gestoes'
    | '/terceiros'
    | '/sessoes'
    | '/tesouraria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/contabilidade/auditoria'
    | '/_authenticated/orgs/potencias'
    | '/_authenticated/gestoes/cargos'
    | '/_authenticated/irmaos/$id'
    | '/_authenticated/irmaos/novo'
    | '/_authenticated/relatorios/frequencia'
    | '/_authenticated/relatorios/inadimplentes'
    | '/_authenticated/sessoes/$id'
    | '/_authenticated/tesouraria/contas'
    | '/_authenticated/tesouraria/contas-pagar'
    | '/_authenticated/tesouraria/plano-contas'
    | '/_authenticated/irmaos/'
    | '/_authenticated/orgs/'
    | '/_authenticated/gestoes/'
    | '/_authenticated/terceiros/'
    | '/_authenticated/sessoes/'
    | '/_authenticated/tesouraria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/auditoria': {
      id: '/_authenticated/contabilidade/auditoria'
      path: '/contabilidade/auditoria'
      fullPath: '/contabilidade/auditoria'
      preLoaderRoute: typeof AuthenticatedContabilidadeAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/potencias': {
      id: '/_authenticated/orgs/potencias'
      path: '/orgs/potencias'
      fullPath: '/orgs/potencias'
      preLoaderRoute: typeof AuthenticatedOrgsPotenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestoes/cargos': {
      id: '/_authenticated/gestoes/cargos'
      path: '/gestoes/cargos'
      fullPath: '/gestoes/cargos'
      preLoaderRoute: typeof AuthenticatedGestoesCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestoes/': {
      id: '/_authenticated/gestoes/'
      path: '/gestoes'
      fullPath: '/gestoes/'
      preLoaderRoute: typeof AuthenticatedGestoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terceiros/': {
      id: '/_authenticated/terceiros/'
      path: '/terceiros'
      fullPath: '/terceiros/'
      preLoaderRoute: typeof AuthenticatedTerceirosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/': {
      id: '/_authenticated/tesouraria/'
      path: '/tesouraria'
      fullPath: '/tesouraria/'
      preLoaderRoute: typeof AuthenticatedTesourariaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/': {
      id: '/_authenticated/sessoes/'
      path: '/sessoes'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof AuthenticatedSessoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/': {
      id: '/_authenticated/irmaos/'
      path: '/irmaos'
      fullPath: '/irmaos/'
      preLoaderRoute: typeof AuthenticatedIrmaosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/plano-contas': {
      id: '/_authenticated/tesouraria/plano-contas'
      path: '/tesouraria/plano-contas'
      fullPath: '/tesouraria/plano-contas'
      preLoaderRoute: typeof AuthenticatedTesourariaPlanoContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/contas': {
      id: '/_authenticated/tesouraria/contas'
      path: '/tesouraria/contas'
      fullPath: '/tesouraria/contas'
      preLoaderRoute: typeof AuthenticatedTesourariaContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/contas-pagar': {
      id: '/_authenticated/tesouraria/contas-pagar'
      path: '/tesouraria/contas-pagar'
      fullPath: '/tesouraria/contas-pagar'
      preLoaderRoute: typeof AuthenticatedTesourariaContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/$id': {
      id: '/_authenticated/sessoes/$id'
      path: '/sessoes/$id'
      fullPath: '/sessoes/$id'
      preLoaderRoute: typeof AuthenticatedSessoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/inadimplentes': {
      id: '/_authenticated/relatorios/inadimplentes'
      path: '/relatorios/inadimplentes'
      fullPath: '/relatorios/inadimplentes'
      preLoaderRoute: typeof AuthenticatedRelatoriosInadimplentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/frequencia': {
      id: '/_authenticated/relatorios/frequencia'
      path: '/relatorios/frequencia'
      fullPath: '/relatorios/frequencia'
      preLoaderRoute: typeof AuthenticatedRelatoriosFrequenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/novo': {
      id: '/_authenticated/irmaos/novo'
      path: '/irmaos/novo'
      fullPath: '/irmaos/novo'
      preLoaderRoute: typeof AuthenticatedIrmaosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/$id': {
      id: '/_authenticated/irmaos/$id'
      path: '/irmaos/$id'
      fullPath: '/irmaos/$id'
      preLoaderRoute: typeof AuthenticatedIrmaosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedContabilidadeAuditoriaRoute: typeof AuthenticatedContabilidadeAuditoriaRoute
  AuthenticatedOrgsPotenciasRoute: typeof AuthenticatedOrgsPotenciasRoute
  AuthenticatedGestoesCargosRoute: typeof AuthenticatedGestoesCargosRoute
  AuthenticatedIrmaosIdRoute: typeof AuthenticatedIrmaosIdRoute
  AuthenticatedIrmaosNovoRoute: typeof AuthenticatedIrmaosNovoRoute
  AuthenticatedRelatoriosFrequenciaRoute: typeof AuthenticatedRelatoriosFrequenciaRoute
  AuthenticatedRelatoriosInadimplentesRoute: typeof AuthenticatedRelatoriosInadimplentesRoute
  AuthenticatedSessoesIdRoute: typeof AuthenticatedSessoesIdRoute
  AuthenticatedTesourariaContasRoute: typeof AuthenticatedTesourariaContasRoute
  AuthenticatedTesourariaContasPagarRoute: typeof AuthenticatedTesourariaContasPagarRoute
  AuthenticatedTesourariaPlanoContasRoute: typeof AuthenticatedTesourariaPlanoContasRoute
  AuthenticatedIrmaosIndexRoute: typeof AuthenticatedIrmaosIndexRoute
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
  AuthenticatedGestoesIndexRoute: typeof AuthenticatedGestoesIndexRoute
  AuthenticatedTerceirosIndexRoute: typeof AuthenticatedTerceirosIndexRoute
  AuthenticatedSessoesIndexRoute: typeof AuthenticatedSessoesIndexRoute
  AuthenticatedTesourariaIndexRoute: typeof AuthenticatedTesourariaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedContabilidadeAuditoriaRoute:
    AuthenticatedContabilidadeAuditoriaRoute,
  AuthenticatedOrgsPotenciasRoute: AuthenticatedOrgsPotenciasRoute,
  AuthenticatedGestoesCargosRoute: AuthenticatedGestoesCargosRoute,
  AuthenticatedIrmaosIdRoute: AuthenticatedIrmaosIdRoute,
  AuthenticatedIrmaosNovoRoute: AuthenticatedIrmaosNovoRoute,
  AuthenticatedRelatoriosFrequenciaRoute:
    AuthenticatedRelatoriosFrequenciaRoute,
  AuthenticatedRelatoriosInadimplentesRoute:
    AuthenticatedRelatoriosInadimplentesRoute,
  AuthenticatedSessoesIdRoute: AuthenticatedSessoesIdRoute,
  AuthenticatedTesourariaContasRoute: AuthenticatedTesourariaContasRoute,
  AuthenticatedTesourariaContasPagarRoute: AuthenticatedTesourariaContasPagarRoute,
  AuthenticatedTesourariaPlanoContasRoute:
    AuthenticatedTesourariaPlanoContasRoute,
  AuthenticatedIrmaosIndexRoute: AuthenticatedIrmaosIndexRoute,
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
  AuthenticatedGestoesIndexRoute: AuthenticatedGestoesIndexRoute,
  AuthenticatedTerceirosIndexRoute: AuthenticatedTerceirosIndexRoute,
  AuthenticatedSessoesIndexRoute: AuthenticatedSessoesIndexRoute,
  AuthenticatedTesourariaIndexRoute: AuthenticatedTesourariaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
