/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AceiteTermosRouteImport } from './routes/aceite-termos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPainelRouteRouteImport } from './routes/_authenticated/painel/route'
import { Route as AuthenticatedAdministracaoAuditoriaRouteImport } from './routes/_authenticated/administracao/auditoria'
import { Route as AuthenticatedAdministracaoBackupsRouteImport } from './routes/_authenticated/administracao/backups'
import { Route as AuthenticatedAdministracaoExportarDadosRouteImport } from './routes/_authenticated/administracao/exportar-dados'
import { Route as AuthenticatedAdministracaoResetarFinanceiroRouteImport } from './routes/_authenticated/administracao/resetar-financeiro'
import { Route as AuthenticatedBibliotecaIndexRouteImport } from './routes/_authenticated/biblioteca/index'
import { Route as AuthenticatedCalendarioIndexRouteImport } from './routes/_authenticated/calendario/index'
import { Route as AuthenticatedComissoesIndexRouteImport } from './routes/_authenticated/comissoes/index'
import { Route as AuthenticatedComunicacoesIndexRouteImport } from './routes/_authenticated/comunicacoes/index'
import { Route as AuthenticatedContaSegurancaRouteImport } from './routes/_authenticated/conta/seguranca'
import { Route as AuthenticatedContabilidadeAuditoriaRouteImport } from './routes/_authenticated/contabilidade/auditoria'
import { Route as AuthenticatedContabilidadeBalanceteRouteImport } from './routes/_authenticated/contabilidade/balancete'
import { Route as AuthenticatedContabilidadeDiarioRouteImport } from './routes/_authenticated/contabilidade/diario'
import { Route as AuthenticatedContabilidadeDreRouteImport } from './routes/_authenticated/contabilidade/dre'
import { Route as AuthenticatedContabilidadeDreOrcadoRouteImport } from './routes/_authenticated/contabilidade/dre-orcado'
import { Route as AuthenticatedContabilidadeFechamentoRouteImport } from './routes/_authenticated/contabilidade/fechamento'
import { Route as AuthenticatedContabilidadeFluxoCaixaRouteImport } from './routes/_authenticated/contabilidade/fluxo-caixa'
import { Route as AuthenticatedContabilidadeOrcamentoRouteImport } from './routes/_authenticated/contabilidade/orcamento'
import { Route as AuthenticatedContabilidadeRazaoRouteImport } from './routes/_authenticated/contabilidade/razao'
import { Route as AuthenticatedEnquetesIndexRouteImport } from './routes/_authenticated/enquetes/index'
import { Route as AuthenticatedEnsinoImportarCalendarioRouteImport } from './routes/_authenticated/ensino/importar-calendario'
import { Route as AuthenticatedEnsinoImportarPdfSessoesRouteImport } from './routes/_authenticated/ensino/importar-pdf-sessoes'
import { Route as AuthenticatedEnsinoPlanosRouteImport } from './routes/_authenticated/ensino/planos'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos/index'
import { Route as AuthenticatedGestoesIndexRouteImport } from './routes/_authenticated/gestoes/index'
import { Route as AuthenticatedGestoesCargosRouteImport } from './routes/_authenticated/gestoes/cargos'
import { Route as AuthenticatedIntersticoIndexRouteImport } from './routes/_authenticated/interstico/index'
import { Route as AuthenticatedIrmaosIndexRouteImport } from './routes/_authenticated/irmaos/index'
import { Route as AuthenticatedIrmaosIdRouteImport } from './routes/_authenticated/irmaos/$id'
import { Route as AuthenticatedIrmaosNovoRouteImport } from './routes/_authenticated/irmaos/novo'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs/index'
import { Route as AuthenticatedOrgsPotenciasRouteImport } from './routes/_authenticated/orgs/potencias'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel/index'
import { Route as AuthenticatedPainelComunicacoesRouteImport } from './routes/_authenticated/painel/comunicacoes'
import { Route as AuthenticatedPainelDadosRouteImport } from './routes/_authenticated/painel/dados'
import { Route as AuthenticatedPainelEventosRouteImport } from './routes/_authenticated/painel/eventos'
import { Route as AuthenticatedPainelFinanceiroRouteImport } from './routes/_authenticated/painel/financeiro'
import { Route as AuthenticatedPainelFrequenciaRouteImport } from './routes/_authenticated/painel/frequencia'
import { Route as AuthenticatedPainelQuitacaoRouteImport } from './routes/_authenticated/painel/quitacao'
import { Route as AuthenticatedPainelSessoesRouteImport } from './routes/_authenticated/painel/sessoes'
import { Route as AuthenticatedRelatoriosFrequenciaRouteImport } from './routes/_authenticated/relatorios/frequencia'
import { Route as AuthenticatedRelatoriosInadimplentesRouteImport } from './routes/_authenticated/relatorios/inadimplentes'
import { Route as AuthenticatedSessoesIndexRouteImport } from './routes/_authenticated/sessoes/index'
import { Route as AuthenticatedSessoesIdRouteImport } from './routes/_authenticated/sessoes/$id'
import { Route as AuthenticatedSgcabCobrancasRouteImport } from './routes/_authenticated/sgcab/cobrancas'
import { Route as AuthenticatedTerceirosIndexRouteImport } from './routes/_authenticated/terceiros/index'
import { Route as AuthenticatedTesourariaIndexRouteImport } from './routes/_authenticated/tesouraria/index'
import { Route as AuthenticatedTesourariaConciliacaoRouteImport } from './routes/_authenticated/tesouraria/conciliacao'
import { Route as AuthenticatedTesourariaContasRouteImport } from './routes/_authenticated/tesouraria/contas'
import { Route as AuthenticatedTesourariaContasPagarRouteImport } from './routes/_authenticated/tesouraria/contas-pagar'
import { Route as AuthenticatedTesourariaMovimentosRouteImport } from './routes/_authenticated/tesouraria/movimentos'
import { Route as AuthenticatedTesourariaParametrosRouteImport } from './routes/_authenticated/tesouraria/parametros'
import { Route as AuthenticatedTesourariaParcelamentosRouteImport } from './routes/_authenticated/tesouraria/parcelamentos'
import { Route as AuthenticatedTesourariaPlanoContasRouteImport } from './routes/_authenticated/tesouraria/plano-contas'
import { Route as AuthenticatedTesourariaRecibosRouteImport } from './routes/_authenticated/tesouraria/recibos'
import { Route as AuthenticatedTesourariaRecorrentesRouteImport } from './routes/_authenticated/tesouraria/recorrentes'
import { Route as AuthenticatedTesourariaTabelaValoresRouteImport } from './routes/_authenticated/tesouraria/tabela-valores'
import { Route as AuthenticatedTesourariaTroncoRouteImport } from './routes/_authenticated/tesouraria/tronco'
import { Route as AuthenticatedUsuariosIndexRouteImport } from './routes/_authenticated/usuarios/index'
import { Route as AuthenticatedTesourariaFaturasIndexRouteImport } from './routes/_authenticated/tesouraria/faturas/index'
import { Route as AuthenticatedTesourariaFaturasIdRouteImport } from './routes/_authenticated/tesouraria/faturas/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AceiteTermosRoute = AceiteTermosRouteImport.update({
  id: '/aceite-termos',
  path: '/aceite-termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRouteRoute =
  AuthenticatedPainelRouteRouteImport.update({
    id: '/painel',
    path: '/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoAuditoriaRoute =
  AuthenticatedAdministracaoAuditoriaRouteImport.update({
    id: '/administracao/auditoria',
    path: '/administracao/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoBackupsRoute =
  AuthenticatedAdministracaoBackupsRouteImport.update({
    id: '/administracao/backups',
    path: '/administracao/backups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoExportarDadosRoute =
  AuthenticatedAdministracaoExportarDadosRouteImport.update({
    id: '/administracao/exportar-dados',
    path: '/administracao/exportar-dados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoResetarFinanceiroRoute =
  AuthenticatedAdministracaoResetarFinanceiroRouteImport.update({
    id: '/administracao/resetar-financeiro',
    path: '/administracao/resetar-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaIndexRoute =
  AuthenticatedBibliotecaIndexRouteImport.update({
    id: '/biblioteca/',
    path: '/biblioteca/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioIndexRoute =
  AuthenticatedCalendarioIndexRouteImport.update({
    id: '/calendario/',
    path: '/calendario/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissoesIndexRoute =
  AuthenticatedComissoesIndexRouteImport.update({
    id: '/comissoes/',
    path: '/comissoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicacoesIndexRoute =
  AuthenticatedComunicacoesIndexRouteImport.update({
    id: '/comunicacoes/',
    path: '/comunicacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaSegurancaRoute =
  AuthenticatedContaSegurancaRouteImport.update({
    id: '/conta/seguranca',
    path: '/conta/seguranca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeAuditoriaRoute =
  AuthenticatedContabilidadeAuditoriaRouteImport.update({
    id: '/contabilidade/auditoria',
    path: '/contabilidade/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeBalanceteRoute =
  AuthenticatedContabilidadeBalanceteRouteImport.update({
    id: '/contabilidade/balancete',
    path: '/contabilidade/balancete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeDiarioRoute =
  AuthenticatedContabilidadeDiarioRouteImport.update({
    id: '/contabilidade/diario',
    path: '/contabilidade/diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeDreRoute =
  AuthenticatedContabilidadeDreRouteImport.update({
    id: '/contabilidade/dre',
    path: '/contabilidade/dre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeDreOrcadoRoute =
  AuthenticatedContabilidadeDreOrcadoRouteImport.update({
    id: '/contabilidade/dre-orcado',
    path: '/contabilidade/dre-orcado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeFechamentoRoute =
  AuthenticatedContabilidadeFechamentoRouteImport.update({
    id: '/contabilidade/fechamento',
    path: '/contabilidade/fechamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeFluxoCaixaRoute =
  AuthenticatedContabilidadeFluxoCaixaRouteImport.update({
    id: '/contabilidade/fluxo-caixa',
    path: '/contabilidade/fluxo-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeOrcamentoRoute =
  AuthenticatedContabilidadeOrcamentoRouteImport.update({
    id: '/contabilidade/orcamento',
    path: '/contabilidade/orcamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeRazaoRoute =
  AuthenticatedContabilidadeRazaoRouteImport.update({
    id: '/contabilidade/razao',
    path: '/contabilidade/razao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnquetesIndexRoute =
  AuthenticatedEnquetesIndexRouteImport.update({
    id: '/enquetes/',
    path: '/enquetes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnsinoImportarCalendarioRoute =
  AuthenticatedEnsinoImportarCalendarioRouteImport.update({
    id: '/ensino/importar-calendario',
    path: '/ensino/importar-calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnsinoImportarPdfSessoesRoute =
  AuthenticatedEnsinoImportarPdfSessoesRouteImport.update({
    id: '/ensino/importar-pdf-sessoes',
    path: '/ensino/importar-pdf-sessoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnsinoPlanosRoute =
  AuthenticatedEnsinoPlanosRouteImport.update({
    id: '/ensino/planos',
    path: '/ensino/planos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestoesIndexRoute =
  AuthenticatedGestoesIndexRouteImport.update({
    id: '/gestoes/',
    path: '/gestoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestoesCargosRoute =
  AuthenticatedGestoesCargosRouteImport.update({
    id: '/gestoes/cargos',
    path: '/gestoes/cargos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntersticoIndexRoute =
  AuthenticatedIntersticoIndexRouteImport.update({
    id: '/interstico/',
    path: '/interstico/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIrmaosIndexRoute =
  AuthenticatedIrmaosIndexRouteImport.update({
    id: '/irmaos/',
    path: '/irmaos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIrmaosIdRoute = AuthenticatedIrmaosIdRouteImport.update({
  id: '/irmaos/$id',
  path: '/irmaos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIrmaosNovoRoute = AuthenticatedIrmaosNovoRouteImport.update({
  id: '/irmaos/novo',
  path: '/irmaos/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgsPotenciasRoute =
  AuthenticatedOrgsPotenciasRouteImport.update({
    id: '/orgs/potencias',
    path: '/orgs/potencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelComunicacoesRoute =
  AuthenticatedPainelComunicacoesRouteImport.update({
    id: '/comunicacoes',
    path: '/comunicacoes',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelDadosRoute =
  AuthenticatedPainelDadosRouteImport.update({
    id: '/dados',
    path: '/dados',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelEventosRoute =
  AuthenticatedPainelEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelFinanceiroRoute =
  AuthenticatedPainelFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelFrequenciaRoute =
  AuthenticatedPainelFrequenciaRouteImport.update({
    id: '/frequencia',
    path: '/frequencia',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelQuitacaoRoute =
  AuthenticatedPainelQuitacaoRouteImport.update({
    id: '/quitacao',
    path: '/quitacao',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedPainelSessoesRoute =
  AuthenticatedPainelSessoesRouteImport.update({
    id: '/sessoes',
    path: '/sessoes',
    getParentRoute: () => AuthenticatedPainelRouteRoute,
  } as any)
const AuthenticatedRelatoriosFrequenciaRoute =
  AuthenticatedRelatoriosFrequenciaRouteImport.update({
    id: '/relatorios/frequencia',
    path: '/relatorios/frequencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosInadimplentesRoute =
  AuthenticatedRelatoriosInadimplentesRouteImport.update({
    id: '/relatorios/inadimplentes',
    path: '/relatorios/inadimplentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIndexRoute =
  AuthenticatedSessoesIndexRouteImport.update({
    id: '/sessoes/',
    path: '/sessoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIdRoute = AuthenticatedSessoesIdRouteImport.update({
  id: '/sessoes/$id',
  path: '/sessoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSgcabCobrancasRoute =
  AuthenticatedSgcabCobrancasRouteImport.update({
    id: '/sgcab/cobrancas',
    path: '/sgcab/cobrancas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerceirosIndexRoute =
  AuthenticatedTerceirosIndexRouteImport.update({
    id: '/terceiros/',
    path: '/terceiros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaIndexRoute =
  AuthenticatedTesourariaIndexRouteImport.update({
    id: '/tesouraria/',
    path: '/tesouraria/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaConciliacaoRoute =
  AuthenticatedTesourariaConciliacaoRouteImport.update({
    id: '/tesouraria/conciliacao',
    path: '/tesouraria/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaContasRoute =
  AuthenticatedTesourariaContasRouteImport.update({
    id: '/tesouraria/contas',
    path: '/tesouraria/contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaContasPagarRoute =
  AuthenticatedTesourariaContasPagarRouteImport.update({
    id: '/tesouraria/contas-pagar',
    path: '/tesouraria/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaMovimentosRoute =
  AuthenticatedTesourariaMovimentosRouteImport.update({
    id: '/tesouraria/movimentos',
    path: '/tesouraria/movimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaParametrosRoute =
  AuthenticatedTesourariaParametrosRouteImport.update({
    id: '/tesouraria/parametros',
    path: '/tesouraria/parametros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaParcelamentosRoute =
  AuthenticatedTesourariaParcelamentosRouteImport.update({
    id: '/tesouraria/parcelamentos',
    path: '/tesouraria/parcelamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaPlanoContasRoute =
  AuthenticatedTesourariaPlanoContasRouteImport.update({
    id: '/tesouraria/plano-contas',
    path: '/tesouraria/plano-contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaRecibosRoute =
  AuthenticatedTesourariaRecibosRouteImport.update({
    id: '/tesouraria/recibos',
    path: '/tesouraria/recibos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaRecorrentesRoute =
  AuthenticatedTesourariaRecorrentesRouteImport.update({
    id: '/tesouraria/recorrentes',
    path: '/tesouraria/recorrentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaTabelaValoresRoute =
  AuthenticatedTesourariaTabelaValoresRouteImport.update({
    id: '/tesouraria/tabela-valores',
    path: '/tesouraria/tabela-valores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaTroncoRoute =
  AuthenticatedTesourariaTroncoRouteImport.update({
    id: '/tesouraria/tronco',
    path: '/tesouraria/tronco',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosIndexRoute =
  AuthenticatedUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaFaturasIndexRoute =
  AuthenticatedTesourariaFaturasIndexRouteImport.update({
    id: '/tesouraria/faturas/',
    path: '/tesouraria/faturas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaFaturasIdRoute =
  AuthenticatedTesourariaFaturasIdRouteImport.update({
    id: '/tesouraria/faturas/$id',
    path: '/tesouraria/faturas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceite-termos': typeof AceiteTermosRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/painel': typeof AuthenticatedPainelRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/administracao/auditoria': typeof AuthenticatedAdministracaoAuditoriaRoute
  '/administracao/backups': typeof AuthenticatedAdministracaoBackupsRoute
  '/administracao/exportar-dados': typeof AuthenticatedAdministracaoExportarDadosRoute
  '/administracao/resetar-financeiro': typeof AuthenticatedAdministracaoResetarFinanceiroRoute
  '/conta/seguranca': typeof AuthenticatedContaSegurancaRoute
  '/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/contabilidade/balancete': typeof AuthenticatedContabilidadeBalanceteRoute
  '/contabilidade/diario': typeof AuthenticatedContabilidadeDiarioRoute
  '/contabilidade/dre': typeof AuthenticatedContabilidadeDreRoute
  '/contabilidade/dre-orcado': typeof AuthenticatedContabilidadeDreOrcadoRoute
  '/contabilidade/fechamento': typeof AuthenticatedContabilidadeFechamentoRoute
  '/contabilidade/fluxo-caixa': typeof AuthenticatedContabilidadeFluxoCaixaRoute
  '/contabilidade/orcamento': typeof AuthenticatedContabilidadeOrcamentoRoute
  '/contabilidade/razao': typeof AuthenticatedContabilidadeRazaoRoute
  '/ensino/importar-calendario': typeof AuthenticatedEnsinoImportarCalendarioRoute
  '/ensino/importar-pdf-sessoes': typeof AuthenticatedEnsinoImportarPdfSessoesRoute
  '/ensino/planos': typeof AuthenticatedEnsinoPlanosRoute
  '/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/painel/comunicacoes': typeof AuthenticatedPainelComunicacoesRoute
  '/painel/dados': typeof AuthenticatedPainelDadosRoute
  '/painel/eventos': typeof AuthenticatedPainelEventosRoute
  '/painel/financeiro': typeof AuthenticatedPainelFinanceiroRoute
  '/painel/frequencia': typeof AuthenticatedPainelFrequenciaRoute
  '/painel/quitacao': typeof AuthenticatedPainelQuitacaoRoute
  '/painel/sessoes': typeof AuthenticatedPainelSessoesRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/sgcab/cobrancas': typeof AuthenticatedSgcabCobrancasRoute
  '/tesouraria/conciliacao': typeof AuthenticatedTesourariaConciliacaoRoute
  '/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/tesouraria/movimentos': typeof AuthenticatedTesourariaMovimentosRoute
  '/tesouraria/parametros': typeof AuthenticatedTesourariaParametrosRoute
  '/tesouraria/parcelamentos': typeof AuthenticatedTesourariaParcelamentosRoute
  '/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/tesouraria/recibos': typeof AuthenticatedTesourariaRecibosRoute
  '/tesouraria/recorrentes': typeof AuthenticatedTesourariaRecorrentesRoute
  '/tesouraria/tabela-valores': typeof AuthenticatedTesourariaTabelaValoresRoute
  '/tesouraria/tronco': typeof AuthenticatedTesourariaTroncoRoute
  '/biblioteca/': typeof AuthenticatedBibliotecaIndexRoute
  '/calendario/': typeof AuthenticatedCalendarioIndexRoute
  '/comissoes/': typeof AuthenticatedComissoesIndexRoute
  '/comunicacoes/': typeof AuthenticatedComunicacoesIndexRoute
  '/enquetes/': typeof AuthenticatedEnquetesIndexRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
  '/gestoes/': typeof AuthenticatedGestoesIndexRoute
  '/interstico/': typeof AuthenticatedIntersticoIndexRoute
  '/irmaos/': typeof AuthenticatedIrmaosIndexRoute
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/terceiros/': typeof AuthenticatedTerceirosIndexRoute
  '/tesouraria/': typeof AuthenticatedTesourariaIndexRoute
  '/usuarios/': typeof AuthenticatedUsuariosIndexRoute
  '/tesouraria/faturas/$id': typeof AuthenticatedTesourariaFaturasIdRoute
  '/tesouraria/faturas/': typeof AuthenticatedTesourariaFaturasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceite-termos': typeof AceiteTermosRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/administracao/auditoria': typeof AuthenticatedAdministracaoAuditoriaRoute
  '/administracao/backups': typeof AuthenticatedAdministracaoBackupsRoute
  '/administracao/exportar-dados': typeof AuthenticatedAdministracaoExportarDadosRoute
  '/administracao/resetar-financeiro': typeof AuthenticatedAdministracaoResetarFinanceiroRoute
  '/conta/seguranca': typeof AuthenticatedContaSegurancaRoute
  '/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/contabilidade/balancete': typeof AuthenticatedContabilidadeBalanceteRoute
  '/contabilidade/diario': typeof AuthenticatedContabilidadeDiarioRoute
  '/contabilidade/dre': typeof AuthenticatedContabilidadeDreRoute
  '/contabilidade/dre-orcado': typeof AuthenticatedContabilidadeDreOrcadoRoute
  '/contabilidade/fechamento': typeof AuthenticatedContabilidadeFechamentoRoute
  '/contabilidade/fluxo-caixa': typeof AuthenticatedContabilidadeFluxoCaixaRoute
  '/contabilidade/orcamento': typeof AuthenticatedContabilidadeOrcamentoRoute
  '/contabilidade/razao': typeof AuthenticatedContabilidadeRazaoRoute
  '/ensino/importar-calendario': typeof AuthenticatedEnsinoImportarCalendarioRoute
  '/ensino/importar-pdf-sessoes': typeof AuthenticatedEnsinoImportarPdfSessoesRoute
  '/ensino/planos': typeof AuthenticatedEnsinoPlanosRoute
  '/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/painel/comunicacoes': typeof AuthenticatedPainelComunicacoesRoute
  '/painel/dados': typeof AuthenticatedPainelDadosRoute
  '/painel/eventos': typeof AuthenticatedPainelEventosRoute
  '/painel/financeiro': typeof AuthenticatedPainelFinanceiroRoute
  '/painel/frequencia': typeof AuthenticatedPainelFrequenciaRoute
  '/painel/quitacao': typeof AuthenticatedPainelQuitacaoRoute
  '/painel/sessoes': typeof AuthenticatedPainelSessoesRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/sgcab/cobrancas': typeof AuthenticatedSgcabCobrancasRoute
  '/tesouraria/conciliacao': typeof AuthenticatedTesourariaConciliacaoRoute
  '/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/tesouraria/movimentos': typeof AuthenticatedTesourariaMovimentosRoute
  '/tesouraria/parametros': typeof AuthenticatedTesourariaParametrosRoute
  '/tesouraria/parcelamentos': typeof AuthenticatedTesourariaParcelamentosRoute
  '/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/tesouraria/recibos': typeof AuthenticatedTesourariaRecibosRoute
  '/tesouraria/recorrentes': typeof AuthenticatedTesourariaRecorrentesRoute
  '/tesouraria/tabela-valores': typeof AuthenticatedTesourariaTabelaValoresRoute
  '/tesouraria/tronco': typeof AuthenticatedTesourariaTroncoRoute
  '/biblioteca': typeof AuthenticatedBibliotecaIndexRoute
  '/calendario': typeof AuthenticatedCalendarioIndexRoute
  '/comissoes': typeof AuthenticatedComissoesIndexRoute
  '/comunicacoes': typeof AuthenticatedComunicacoesIndexRoute
  '/enquetes': typeof AuthenticatedEnquetesIndexRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
  '/gestoes': typeof AuthenticatedGestoesIndexRoute
  '/interstico': typeof AuthenticatedIntersticoIndexRoute
  '/irmaos': typeof AuthenticatedIrmaosIndexRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/sessoes': typeof AuthenticatedSessoesIndexRoute
  '/terceiros': typeof AuthenticatedTerceirosIndexRoute
  '/tesouraria': typeof AuthenticatedTesourariaIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
  '/tesouraria/faturas/$id': typeof AuthenticatedTesourariaFaturasIdRoute
  '/tesouraria/faturas': typeof AuthenticatedTesourariaFaturasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aceite-termos': typeof AceiteTermosRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/administracao/auditoria': typeof AuthenticatedAdministracaoAuditoriaRoute
  '/_authenticated/administracao/backups': typeof AuthenticatedAdministracaoBackupsRoute
  '/_authenticated/administracao/exportar-dados': typeof AuthenticatedAdministracaoExportarDadosRoute
  '/_authenticated/administracao/resetar-financeiro': typeof AuthenticatedAdministracaoResetarFinanceiroRoute
  '/_authenticated/conta/seguranca': typeof AuthenticatedContaSegurancaRoute
  '/_authenticated/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/_authenticated/contabilidade/balancete': typeof AuthenticatedContabilidadeBalanceteRoute
  '/_authenticated/contabilidade/diario': typeof AuthenticatedContabilidadeDiarioRoute
  '/_authenticated/contabilidade/dre': typeof AuthenticatedContabilidadeDreRoute
  '/_authenticated/contabilidade/dre-orcado': typeof AuthenticatedContabilidadeDreOrcadoRoute
  '/_authenticated/contabilidade/fechamento': typeof AuthenticatedContabilidadeFechamentoRoute
  '/_authenticated/contabilidade/fluxo-caixa': typeof AuthenticatedContabilidadeFluxoCaixaRoute
  '/_authenticated/contabilidade/orcamento': typeof AuthenticatedContabilidadeOrcamentoRoute
  '/_authenticated/contabilidade/razao': typeof AuthenticatedContabilidadeRazaoRoute
  '/_authenticated/ensino/importar-calendario': typeof AuthenticatedEnsinoImportarCalendarioRoute
  '/_authenticated/ensino/importar-pdf-sessoes': typeof AuthenticatedEnsinoImportarPdfSessoesRoute
  '/_authenticated/ensino/planos': typeof AuthenticatedEnsinoPlanosRoute
  '/_authenticated/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/_authenticated/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/_authenticated/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/_authenticated/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/_authenticated/painel/comunicacoes': typeof AuthenticatedPainelComunicacoesRoute
  '/_authenticated/painel/dados': typeof AuthenticatedPainelDadosRoute
  '/_authenticated/painel/eventos': typeof AuthenticatedPainelEventosRoute
  '/_authenticated/painel/financeiro': typeof AuthenticatedPainelFinanceiroRoute
  '/_authenticated/painel/frequencia': typeof AuthenticatedPainelFrequenciaRoute
  '/_authenticated/painel/quitacao': typeof AuthenticatedPainelQuitacaoRoute
  '/_authenticated/painel/sessoes': typeof AuthenticatedPainelSessoesRoute
  '/_authenticated/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/_authenticated/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/_authenticated/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/_authenticated/sgcab/cobrancas': typeof AuthenticatedSgcabCobrancasRoute
  '/_authenticated/tesouraria/conciliacao': typeof AuthenticatedTesourariaConciliacaoRoute
  '/_authenticated/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/_authenticated/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/_authenticated/tesouraria/movimentos': typeof AuthenticatedTesourariaMovimentosRoute
  '/_authenticated/tesouraria/parametros': typeof AuthenticatedTesourariaParametrosRoute
  '/_authenticated/tesouraria/parcelamentos': typeof AuthenticatedTesourariaParcelamentosRoute
  '/_authenticated/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/_authenticated/tesouraria/recibos': typeof AuthenticatedTesourariaRecibosRoute
  '/_authenticated/tesouraria/recorrentes': typeof AuthenticatedTesourariaRecorrentesRoute
  '/_authenticated/tesouraria/tabela-valores': typeof AuthenticatedTesourariaTabelaValoresRoute
  '/_authenticated/tesouraria/tronco': typeof AuthenticatedTesourariaTroncoRoute
  '/_authenticated/biblioteca/': typeof AuthenticatedBibliotecaIndexRoute
  '/_authenticated/calendario/': typeof AuthenticatedCalendarioIndexRoute
  '/_authenticated/comissoes/': typeof AuthenticatedComissoesIndexRoute
  '/_authenticated/comunicacoes/': typeof AuthenticatedComunicacoesIndexRoute
  '/_authenticated/enquetes/': typeof AuthenticatedEnquetesIndexRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
  '/_authenticated/gestoes/': typeof AuthenticatedGestoesIndexRoute
  '/_authenticated/interstico/': typeof AuthenticatedIntersticoIndexRoute
  '/_authenticated/irmaos/': typeof AuthenticatedIrmaosIndexRoute
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/_authenticated/terceiros/': typeof AuthenticatedTerceirosIndexRoute
  '/_authenticated/tesouraria/': typeof AuthenticatedTesourariaIndexRoute
  '/_authenticated/usuarios/': typeof AuthenticatedUsuariosIndexRoute
  '/_authenticated/tesouraria/faturas/$id': typeof AuthenticatedTesourariaFaturasIdRoute
  '/_authenticated/tesouraria/faturas/': typeof AuthenticatedTesourariaFaturasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceite-termos'
    | '/auth'
    | '/privacidade'
    | '/trocar-senha'
    | '/painel'
    | '/dashboard'
    | '/administracao/auditoria'
    | '/administracao/backups'
    | '/administracao/exportar-dados'
    | '/administracao/resetar-financeiro'
    | '/conta/seguranca'
    | '/contabilidade/auditoria'
    | '/contabilidade/balancete'
    | '/contabilidade/diario'
    | '/contabilidade/dre'
    | '/contabilidade/dre-orcado'
    | '/contabilidade/fechamento'
    | '/contabilidade/fluxo-caixa'
    | '/contabilidade/orcamento'
    | '/contabilidade/razao'
    | '/ensino/importar-calendario'
    | '/ensino/importar-pdf-sessoes'
    | '/ensino/planos'
    | '/gestoes/cargos'
    | '/irmaos/$id'
    | '/irmaos/novo'
    | '/orgs/potencias'
    | '/painel/comunicacoes'
    | '/painel/dados'
    | '/painel/eventos'
    | '/painel/financeiro'
    | '/painel/frequencia'
    | '/painel/quitacao'
    | '/painel/sessoes'
    | '/relatorios/frequencia'
    | '/relatorios/inadimplentes'
    | '/sessoes/$id'
    | '/sgcab/cobrancas'
    | '/tesouraria/conciliacao'
    | '/tesouraria/contas'
    | '/tesouraria/contas-pagar'
    | '/tesouraria/movimentos'
    | '/tesouraria/parametros'
    | '/tesouraria/parcelamentos'
    | '/tesouraria/plano-contas'
    | '/tesouraria/recibos'
    | '/tesouraria/recorrentes'
    | '/tesouraria/tabela-valores'
    | '/tesouraria/tronco'
    | '/biblioteca/'
    | '/calendario/'
    | '/comissoes/'
    | '/comunicacoes/'
    | '/enquetes/'
    | '/eventos/'
    | '/gestoes/'
    | '/interstico/'
    | '/irmaos/'
    | '/orgs/'
    | '/painel/'
    | '/sessoes/'
    | '/terceiros/'
    | '/tesouraria/'
    | '/usuarios/'
    | '/tesouraria/faturas/$id'
    | '/tesouraria/faturas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceite-termos'
    | '/auth'
    | '/privacidade'
    | '/trocar-senha'
    | '/dashboard'
    | '/administracao/auditoria'
    | '/administracao/backups'
    | '/administracao/exportar-dados'
    | '/administracao/resetar-financeiro'
    | '/conta/seguranca'
    | '/contabilidade/auditoria'
    | '/contabilidade/balancete'
    | '/contabilidade/diario'
    | '/contabilidade/dre'
    | '/contabilidade/dre-orcado'
    | '/contabilidade/fechamento'
    | '/contabilidade/fluxo-caixa'
    | '/contabilidade/orcamento'
    | '/contabilidade/razao'
    | '/ensino/importar-calendario'
    | '/ensino/importar-pdf-sessoes'
    | '/ensino/planos'
    | '/gestoes/cargos'
    | '/irmaos/$id'
    | '/irmaos/novo'
    | '/orgs/potencias'
    | '/painel/comunicacoes'
    | '/painel/dados'
    | '/painel/eventos'
    | '/painel/financeiro'
    | '/painel/frequencia'
    | '/painel/quitacao'
    | '/painel/sessoes'
    | '/relatorios/frequencia'
    | '/relatorios/inadimplentes'
    | '/sessoes/$id'
    | '/sgcab/cobrancas'
    | '/tesouraria/conciliacao'
    | '/tesouraria/contas'
    | '/tesouraria/contas-pagar'
    | '/tesouraria/movimentos'
    | '/tesouraria/parametros'
    | '/tesouraria/parcelamentos'
    | '/tesouraria/plano-contas'
    | '/tesouraria/recibos'
    | '/tesouraria/recorrentes'
    | '/tesouraria/tabela-valores'
    | '/tesouraria/tronco'
    | '/biblioteca'
    | '/calendario'
    | '/comissoes'
    | '/comunicacoes'
    | '/enquetes'
    | '/eventos'
    | '/gestoes'
    | '/interstico'
    | '/irmaos'
    | '/orgs'
    | '/painel'
    | '/sessoes'
    | '/terceiros'
    | '/tesouraria'
    | '/usuarios'
    | '/tesouraria/faturas/$id'
    | '/tesouraria/faturas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aceite-termos'
    | '/auth'
    | '/privacidade'
    | '/trocar-senha'
    | '/_authenticated/painel'
    | '/_authenticated/dashboard'
    | '/_authenticated/administracao/auditoria'
    | '/_authenticated/administracao/backups'
    | '/_authenticated/administracao/exportar-dados'
    | '/_authenticated/administracao/resetar-financeiro'
    | '/_authenticated/conta/seguranca'
    | '/_authenticated/contabilidade/auditoria'
    | '/_authenticated/contabilidade/balancete'
    | '/_authenticated/contabilidade/diario'
    | '/_authenticated/contabilidade/dre'
    | '/_authenticated/contabilidade/dre-orcado'
    | '/_authenticated/contabilidade/fechamento'
    | '/_authenticated/contabilidade/fluxo-caixa'
    | '/_authenticated/contabilidade/orcamento'
    | '/_authenticated/contabilidade/razao'
    | '/_authenticated/ensino/importar-calendario'
    | '/_authenticated/ensino/importar-pdf-sessoes'
    | '/_authenticated/ensino/planos'
    | '/_authenticated/gestoes/cargos'
    | '/_authenticated/irmaos/$id'
    | '/_authenticated/irmaos/novo'
    | '/_authenticated/orgs/potencias'
    | '/_authenticated/painel/comunicacoes'
    | '/_authenticated/painel/dados'
    | '/_authenticated/painel/eventos'
    | '/_authenticated/painel/financeiro'
    | '/_authenticated/painel/frequencia'
    | '/_authenticated/painel/quitacao'
    | '/_authenticated/painel/sessoes'
    | '/_authenticated/relatorios/frequencia'
    | '/_authenticated/relatorios/inadimplentes'
    | '/_authenticated/sessoes/$id'
    | '/_authenticated/sgcab/cobrancas'
    | '/_authenticated/tesouraria/conciliacao'
    | '/_authenticated/tesouraria/contas'
    | '/_authenticated/tesouraria/contas-pagar'
    | '/_authenticated/tesouraria/movimentos'
    | '/_authenticated/tesouraria/parametros'
    | '/_authenticated/tesouraria/parcelamentos'
    | '/_authenticated/tesouraria/plano-contas'
    | '/_authenticated/tesouraria/recibos'
    | '/_authenticated/tesouraria/recorrentes'
    | '/_authenticated/tesouraria/tabela-valores'
    | '/_authenticated/tesouraria/tronco'
    | '/_authenticated/biblioteca/'
    | '/_authenticated/calendario/'
    | '/_authenticated/comissoes/'
    | '/_authenticated/comunicacoes/'
    | '/_authenticated/enquetes/'
    | '/_authenticated/eventos/'
    | '/_authenticated/gestoes/'
    | '/_authenticated/interstico/'
    | '/_authenticated/irmaos/'
    | '/_authenticated/orgs/'
    | '/_authenticated/painel/'
    | '/_authenticated/sessoes/'
    | '/_authenticated/terceiros/'
    | '/_authenticated/tesouraria/'
    | '/_authenticated/usuarios/'
    | '/_authenticated/tesouraria/faturas/$id'
    | '/_authenticated/tesouraria/faturas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AceiteTermosRoute: typeof AceiteTermosRoute
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceite-termos': {
      id: '/aceite-termos'
      path: '/aceite-termos'
      fullPath: '/aceite-termos'
      preLoaderRoute: typeof AceiteTermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/auditoria': {
      id: '/_authenticated/administracao/auditoria'
      path: '/administracao/auditoria'
      fullPath: '/administracao/auditoria'
      preLoaderRoute: typeof AuthenticatedAdministracaoAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/backups': {
      id: '/_authenticated/administracao/backups'
      path: '/administracao/backups'
      fullPath: '/administracao/backups'
      preLoaderRoute: typeof AuthenticatedAdministracaoBackupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/exportar-dados': {
      id: '/_authenticated/administracao/exportar-dados'
      path: '/administracao/exportar-dados'
      fullPath: '/administracao/exportar-dados'
      preLoaderRoute: typeof AuthenticatedAdministracaoExportarDadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/resetar-financeiro': {
      id: '/_authenticated/administracao/resetar-financeiro'
      path: '/administracao/resetar-financeiro'
      fullPath: '/administracao/resetar-financeiro'
      preLoaderRoute: typeof AuthenticatedAdministracaoResetarFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/': {
      id: '/_authenticated/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof AuthenticatedBibliotecaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario/': {
      id: '/_authenticated/calendario/'
      path: '/calendario'
      fullPath: '/calendario/'
      preLoaderRoute: typeof AuthenticatedCalendarioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes/': {
      id: '/_authenticated/comissoes/'
      path: '/comissoes'
      fullPath: '/comissoes/'
      preLoaderRoute: typeof AuthenticatedComissoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacoes/': {
      id: '/_authenticated/comunicacoes/'
      path: '/comunicacoes'
      fullPath: '/comunicacoes/'
      preLoaderRoute: typeof AuthenticatedComunicacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta/seguranca': {
      id: '/_authenticated/conta/seguranca'
      path: '/conta/seguranca'
      fullPath: '/conta/seguranca'
      preLoaderRoute: typeof AuthenticatedContaSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/auditoria': {
      id: '/_authenticated/contabilidade/auditoria'
      path: '/contabilidade/auditoria'
      fullPath: '/contabilidade/auditoria'
      preLoaderRoute: typeof AuthenticatedContabilidadeAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/balancete': {
      id: '/_authenticated/contabilidade/balancete'
      path: '/contabilidade/balancete'
      fullPath: '/contabilidade/balancete'
      preLoaderRoute: typeof AuthenticatedContabilidadeBalanceteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/diario': {
      id: '/_authenticated/contabilidade/diario'
      path: '/contabilidade/diario'
      fullPath: '/contabilidade/diario'
      preLoaderRoute: typeof AuthenticatedContabilidadeDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/dre': {
      id: '/_authenticated/contabilidade/dre'
      path: '/contabilidade/dre'
      fullPath: '/contabilidade/dre'
      preLoaderRoute: typeof AuthenticatedContabilidadeDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/dre-orcado': {
      id: '/_authenticated/contabilidade/dre-orcado'
      path: '/contabilidade/dre-orcado'
      fullPath: '/contabilidade/dre-orcado'
      preLoaderRoute: typeof AuthenticatedContabilidadeDreOrcadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/fechamento': {
      id: '/_authenticated/contabilidade/fechamento'
      path: '/contabilidade/fechamento'
      fullPath: '/contabilidade/fechamento'
      preLoaderRoute: typeof AuthenticatedContabilidadeFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/fluxo-caixa': {
      id: '/_authenticated/contabilidade/fluxo-caixa'
      path: '/contabilidade/fluxo-caixa'
      fullPath: '/contabilidade/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedContabilidadeFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/orcamento': {
      id: '/_authenticated/contabilidade/orcamento'
      path: '/contabilidade/orcamento'
      fullPath: '/contabilidade/orcamento'
      preLoaderRoute: typeof AuthenticatedContabilidadeOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/razao': {
      id: '/_authenticated/contabilidade/razao'
      path: '/contabilidade/razao'
      fullPath: '/contabilidade/razao'
      preLoaderRoute: typeof AuthenticatedContabilidadeRazaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquetes/': {
      id: '/_authenticated/enquetes/'
      path: '/enquetes'
      fullPath: '/enquetes/'
      preLoaderRoute: typeof AuthenticatedEnquetesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ensino/importar-calendario': {
      id: '/_authenticated/ensino/importar-calendario'
      path: '/ensino/importar-calendario'
      fullPath: '/ensino/importar-calendario'
      preLoaderRoute: typeof AuthenticatedEnsinoImportarCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ensino/importar-pdf-sessoes': {
      id: '/_authenticated/ensino/importar-pdf-sessoes'
      path: '/ensino/importar-pdf-sessoes'
      fullPath: '/ensino/importar-pdf-sessoes'
      preLoaderRoute: typeof AuthenticatedEnsinoImportarPdfSessoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ensino/planos': {
      id: '/_authenticated/ensino/planos'
      path: '/ensino/planos'
      fullPath: '/ensino/planos'
      preLoaderRoute: typeof AuthenticatedEnsinoPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestoes/': {
      id: '/_authenticated/gestoes/'
      path: '/gestoes'
      fullPath: '/gestoes/'
      preLoaderRoute: typeof AuthenticatedGestoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestoes/cargos': {
      id: '/_authenticated/gestoes/cargos'
      path: '/gestoes/cargos'
      fullPath: '/gestoes/cargos'
      preLoaderRoute: typeof AuthenticatedGestoesCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interstico/': {
      id: '/_authenticated/interstico/'
      path: '/interstico'
      fullPath: '/interstico/'
      preLoaderRoute: typeof AuthenticatedIntersticoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/': {
      id: '/_authenticated/irmaos/'
      path: '/irmaos'
      fullPath: '/irmaos/'
      preLoaderRoute: typeof AuthenticatedIrmaosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/$id': {
      id: '/_authenticated/irmaos/$id'
      path: '/irmaos/$id'
      fullPath: '/irmaos/$id'
      preLoaderRoute: typeof AuthenticatedIrmaosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/novo': {
      id: '/_authenticated/irmaos/novo'
      path: '/irmaos/novo'
      fullPath: '/irmaos/novo'
      preLoaderRoute: typeof AuthenticatedIrmaosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/potencias': {
      id: '/_authenticated/orgs/potencias'
      path: '/orgs/potencias'
      fullPath: '/orgs/potencias'
      preLoaderRoute: typeof AuthenticatedOrgsPotenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/comunicacoes': {
      id: '/_authenticated/painel/comunicacoes'
      path: '/comunicacoes'
      fullPath: '/painel/comunicacoes'
      preLoaderRoute: typeof AuthenticatedPainelComunicacoesRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/dados': {
      id: '/_authenticated/painel/dados'
      path: '/dados'
      fullPath: '/painel/dados'
      preLoaderRoute: typeof AuthenticatedPainelDadosRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/eventos': {
      id: '/_authenticated/painel/eventos'
      path: '/eventos'
      fullPath: '/painel/eventos'
      preLoaderRoute: typeof AuthenticatedPainelEventosRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/financeiro': {
      id: '/_authenticated/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof AuthenticatedPainelFinanceiroRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/frequencia': {
      id: '/_authenticated/painel/frequencia'
      path: '/frequencia'
      fullPath: '/painel/frequencia'
      preLoaderRoute: typeof AuthenticatedPainelFrequenciaRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/quitacao': {
      id: '/_authenticated/painel/quitacao'
      path: '/quitacao'
      fullPath: '/painel/quitacao'
      preLoaderRoute: typeof AuthenticatedPainelQuitacaoRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/painel/sessoes': {
      id: '/_authenticated/painel/sessoes'
      path: '/sessoes'
      fullPath: '/painel/sessoes'
      preLoaderRoute: typeof AuthenticatedPainelSessoesRouteImport
      parentRoute: typeof AuthenticatedPainelRouteRoute
    }
    '/_authenticated/relatorios/frequencia': {
      id: '/_authenticated/relatorios/frequencia'
      path: '/relatorios/frequencia'
      fullPath: '/relatorios/frequencia'
      preLoaderRoute: typeof AuthenticatedRelatoriosFrequenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/inadimplentes': {
      id: '/_authenticated/relatorios/inadimplentes'
      path: '/relatorios/inadimplentes'
      fullPath: '/relatorios/inadimplentes'
      preLoaderRoute: typeof AuthenticatedRelatoriosInadimplentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/': {
      id: '/_authenticated/sessoes/'
      path: '/sessoes'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof AuthenticatedSessoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/$id': {
      id: '/_authenticated/sessoes/$id'
      path: '/sessoes/$id'
      fullPath: '/sessoes/$id'
      preLoaderRoute: typeof AuthenticatedSessoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sgcab/cobrancas': {
      id: '/_authenticated/sgcab/cobrancas'
      path: '/sgcab/cobrancas'
      fullPath: '/sgcab/cobrancas'
      preLoaderRoute: typeof AuthenticatedSgcabCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terceiros/': {
      id: '/_authenticated/terceiros/'
      path: '/terceiros'
      fullPath: '/terceiros/'
      preLoaderRoute: typeof AuthenticatedTerceirosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/': {
      id: '/_authenticated/tesouraria/'
      path: '/tesouraria'
      fullPath: '/tesouraria/'
      preLoaderRoute: typeof AuthenticatedTesourariaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/conciliacao': {
      id: '/_authenticated/tesouraria/conciliacao'
      path: '/tesouraria/conciliacao'
      fullPath: '/tesouraria/conciliacao'
      preLoaderRoute: typeof AuthenticatedTesourariaConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/contas': {
      id: '/_authenticated/tesouraria/contas'
      path: '/tesouraria/contas'
      fullPath: '/tesouraria/contas'
      preLoaderRoute: typeof AuthenticatedTesourariaContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/contas-pagar': {
      id: '/_authenticated/tesouraria/contas-pagar'
      path: '/tesouraria/contas-pagar'
      fullPath: '/tesouraria/contas-pagar'
      preLoaderRoute: typeof AuthenticatedTesourariaContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/movimentos': {
      id: '/_authenticated/tesouraria/movimentos'
      path: '/tesouraria/movimentos'
      fullPath: '/tesouraria/movimentos'
      preLoaderRoute: typeof AuthenticatedTesourariaMovimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/parametros': {
      id: '/_authenticated/tesouraria/parametros'
      path: '/tesouraria/parametros'
      fullPath: '/tesouraria/parametros'
      preLoaderRoute: typeof AuthenticatedTesourariaParametrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/parcelamentos': {
      id: '/_authenticated/tesouraria/parcelamentos'
      path: '/tesouraria/parcelamentos'
      fullPath: '/tesouraria/parcelamentos'
      preLoaderRoute: typeof AuthenticatedTesourariaParcelamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/plano-contas': {
      id: '/_authenticated/tesouraria/plano-contas'
      path: '/tesouraria/plano-contas'
      fullPath: '/tesouraria/plano-contas'
      preLoaderRoute: typeof AuthenticatedTesourariaPlanoContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/recibos': {
      id: '/_authenticated/tesouraria/recibos'
      path: '/tesouraria/recibos'
      fullPath: '/tesouraria/recibos'
      preLoaderRoute: typeof AuthenticatedTesourariaRecibosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/recorrentes': {
      id: '/_authenticated/tesouraria/recorrentes'
      path: '/tesouraria/recorrentes'
      fullPath: '/tesouraria/recorrentes'
      preLoaderRoute: typeof AuthenticatedTesourariaRecorrentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/tabela-valores': {
      id: '/_authenticated/tesouraria/tabela-valores'
      path: '/tesouraria/tabela-valores'
      fullPath: '/tesouraria/tabela-valores'
      preLoaderRoute: typeof AuthenticatedTesourariaTabelaValoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/tronco': {
      id: '/_authenticated/tesouraria/tronco'
      path: '/tesouraria/tronco'
      fullPath: '/tesouraria/tronco'
      preLoaderRoute: typeof AuthenticatedTesourariaTroncoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios/': {
      id: '/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AuthenticatedUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/faturas/': {
      id: '/_authenticated/tesouraria/faturas/'
      path: '/tesouraria/faturas'
      fullPath: '/tesouraria/faturas/'
      preLoaderRoute: typeof AuthenticatedTesourariaFaturasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/faturas/$id': {
      id: '/_authenticated/tesouraria/faturas/$id'
      path: '/tesouraria/faturas/$id'
      fullPath: '/tesouraria/faturas/$id'
      preLoaderRoute: typeof AuthenticatedTesourariaFaturasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPainelRouteRouteChildren {
  AuthenticatedPainelComunicacoesRoute: typeof AuthenticatedPainelComunicacoesRoute
  AuthenticatedPainelDadosRoute: typeof AuthenticatedPainelDadosRoute
  AuthenticatedPainelEventosRoute: typeof AuthenticatedPainelEventosRoute
  AuthenticatedPainelFinanceiroRoute: typeof AuthenticatedPainelFinanceiroRoute
  AuthenticatedPainelFrequenciaRoute: typeof AuthenticatedPainelFrequenciaRoute
  AuthenticatedPainelQuitacaoRoute: typeof AuthenticatedPainelQuitacaoRoute
  AuthenticatedPainelSessoesRoute: typeof AuthenticatedPainelSessoesRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteRouteChildren: AuthenticatedPainelRouteRouteChildren =
  {
    AuthenticatedPainelComunicacoesRoute: AuthenticatedPainelComunicacoesRoute,
    AuthenticatedPainelDadosRoute: AuthenticatedPainelDadosRoute,
    AuthenticatedPainelEventosRoute: AuthenticatedPainelEventosRoute,
    AuthenticatedPainelFinanceiroRoute: AuthenticatedPainelFinanceiroRoute,
    AuthenticatedPainelFrequenciaRoute: AuthenticatedPainelFrequenciaRoute,
    AuthenticatedPainelQuitacaoRoute: AuthenticatedPainelQuitacaoRoute,
    AuthenticatedPainelSessoesRoute: AuthenticatedPainelSessoesRoute,
    AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  }

const AuthenticatedPainelRouteRouteWithChildren =
  AuthenticatedPainelRouteRoute._addFileChildren(
    AuthenticatedPainelRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRouteRoute: typeof AuthenticatedPainelRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdministracaoAuditoriaRoute: typeof AuthenticatedAdministracaoAuditoriaRoute
  AuthenticatedAdministracaoBackupsRoute: typeof AuthenticatedAdministracaoBackupsRoute
  AuthenticatedAdministracaoExportarDadosRoute: typeof AuthenticatedAdministracaoExportarDadosRoute
  AuthenticatedAdministracaoResetarFinanceiroRoute: typeof AuthenticatedAdministracaoResetarFinanceiroRoute
  AuthenticatedContaSegurancaRoute: typeof AuthenticatedContaSegurancaRoute
  AuthenticatedContabilidadeAuditoriaRoute: typeof AuthenticatedContabilidadeAuditoriaRoute
  AuthenticatedContabilidadeBalanceteRoute: typeof AuthenticatedContabilidadeBalanceteRoute
  AuthenticatedContabilidadeDiarioRoute: typeof AuthenticatedContabilidadeDiarioRoute
  AuthenticatedContabilidadeDreRoute: typeof AuthenticatedContabilidadeDreRoute
  AuthenticatedContabilidadeDreOrcadoRoute: typeof AuthenticatedContabilidadeDreOrcadoRoute
  AuthenticatedContabilidadeFechamentoRoute: typeof AuthenticatedContabilidadeFechamentoRoute
  AuthenticatedContabilidadeFluxoCaixaRoute: typeof AuthenticatedContabilidadeFluxoCaixaRoute
  AuthenticatedContabilidadeOrcamentoRoute: typeof AuthenticatedContabilidadeOrcamentoRoute
  AuthenticatedContabilidadeRazaoRoute: typeof AuthenticatedContabilidadeRazaoRoute
  AuthenticatedEnsinoImportarCalendarioRoute: typeof AuthenticatedEnsinoImportarCalendarioRoute
  AuthenticatedEnsinoImportarPdfSessoesRoute: typeof AuthenticatedEnsinoImportarPdfSessoesRoute
  AuthenticatedEnsinoPlanosRoute: typeof AuthenticatedEnsinoPlanosRoute
  AuthenticatedGestoesCargosRoute: typeof AuthenticatedGestoesCargosRoute
  AuthenticatedIrmaosIdRoute: typeof AuthenticatedIrmaosIdRoute
  AuthenticatedIrmaosNovoRoute: typeof AuthenticatedIrmaosNovoRoute
  AuthenticatedOrgsPotenciasRoute: typeof AuthenticatedOrgsPotenciasRoute
  AuthenticatedRelatoriosFrequenciaRoute: typeof AuthenticatedRelatoriosFrequenciaRoute
  AuthenticatedRelatoriosInadimplentesRoute: typeof AuthenticatedRelatoriosInadimplentesRoute
  AuthenticatedSessoesIdRoute: typeof AuthenticatedSessoesIdRoute
  AuthenticatedSgcabCobrancasRoute: typeof AuthenticatedSgcabCobrancasRoute
  AuthenticatedTesourariaConciliacaoRoute: typeof AuthenticatedTesourariaConciliacaoRoute
  AuthenticatedTesourariaContasRoute: typeof AuthenticatedTesourariaContasRoute
  AuthenticatedTesourariaContasPagarRoute: typeof AuthenticatedTesourariaContasPagarRoute
  AuthenticatedTesourariaMovimentosRoute: typeof AuthenticatedTesourariaMovimentosRoute
  AuthenticatedTesourariaParametrosRoute: typeof AuthenticatedTesourariaParametrosRoute
  AuthenticatedTesourariaParcelamentosRoute: typeof AuthenticatedTesourariaParcelamentosRoute
  AuthenticatedTesourariaPlanoContasRoute: typeof AuthenticatedTesourariaPlanoContasRoute
  AuthenticatedTesourariaRecibosRoute: typeof AuthenticatedTesourariaRecibosRoute
  AuthenticatedTesourariaRecorrentesRoute: typeof AuthenticatedTesourariaRecorrentesRoute
  AuthenticatedTesourariaTabelaValoresRoute: typeof AuthenticatedTesourariaTabelaValoresRoute
  AuthenticatedTesourariaTroncoRoute: typeof AuthenticatedTesourariaTroncoRoute
  AuthenticatedBibliotecaIndexRoute: typeof AuthenticatedBibliotecaIndexRoute
  AuthenticatedCalendarioIndexRoute: typeof AuthenticatedCalendarioIndexRoute
  AuthenticatedComissoesIndexRoute: typeof AuthenticatedComissoesIndexRoute
  AuthenticatedComunicacoesIndexRoute: typeof AuthenticatedComunicacoesIndexRoute
  AuthenticatedEnquetesIndexRoute: typeof AuthenticatedEnquetesIndexRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
  AuthenticatedGestoesIndexRoute: typeof AuthenticatedGestoesIndexRoute
  AuthenticatedIntersticoIndexRoute: typeof AuthenticatedIntersticoIndexRoute
  AuthenticatedIrmaosIndexRoute: typeof AuthenticatedIrmaosIndexRoute
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
  AuthenticatedSessoesIndexRoute: typeof AuthenticatedSessoesIndexRoute
  AuthenticatedTerceirosIndexRoute: typeof AuthenticatedTerceirosIndexRoute
  AuthenticatedTesourariaIndexRoute: typeof AuthenticatedTesourariaIndexRoute
  AuthenticatedUsuariosIndexRoute: typeof AuthenticatedUsuariosIndexRoute
  AuthenticatedTesourariaFaturasIdRoute: typeof AuthenticatedTesourariaFaturasIdRoute
  AuthenticatedTesourariaFaturasIndexRoute: typeof AuthenticatedTesourariaFaturasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRouteRoute: AuthenticatedPainelRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdministracaoAuditoriaRoute:
    AuthenticatedAdministracaoAuditoriaRoute,
  AuthenticatedAdministracaoBackupsRoute:
    AuthenticatedAdministracaoBackupsRoute,
  AuthenticatedAdministracaoExportarDadosRoute:
    AuthenticatedAdministracaoExportarDadosRoute,
  AuthenticatedAdministracaoResetarFinanceiroRoute:
    AuthenticatedAdministracaoResetarFinanceiroRoute,
  AuthenticatedContaSegurancaRoute: AuthenticatedContaSegurancaRoute,
  AuthenticatedContabilidadeAuditoriaRoute:
    AuthenticatedContabilidadeAuditoriaRoute,
  AuthenticatedContabilidadeBalanceteRoute:
    AuthenticatedContabilidadeBalanceteRoute,
  AuthenticatedContabilidadeDiarioRoute: AuthenticatedContabilidadeDiarioRoute,
  AuthenticatedContabilidadeDreRoute: AuthenticatedContabilidadeDreRoute,
  AuthenticatedContabilidadeDreOrcadoRoute:
    AuthenticatedContabilidadeDreOrcadoRoute,
  AuthenticatedContabilidadeFechamentoRoute:
    AuthenticatedContabilidadeFechamentoRoute,
  AuthenticatedContabilidadeFluxoCaixaRoute:
    AuthenticatedContabilidadeFluxoCaixaRoute,
  AuthenticatedContabilidadeOrcamentoRoute:
    AuthenticatedContabilidadeOrcamentoRoute,
  AuthenticatedContabilidadeRazaoRoute: AuthenticatedContabilidadeRazaoRoute,
  AuthenticatedEnsinoImportarCalendarioRoute:
    AuthenticatedEnsinoImportarCalendarioRoute,
  AuthenticatedEnsinoImportarPdfSessoesRoute:
    AuthenticatedEnsinoImportarPdfSessoesRoute,
  AuthenticatedEnsinoPlanosRoute: AuthenticatedEnsinoPlanosRoute,
  AuthenticatedGestoesCargosRoute: AuthenticatedGestoesCargosRoute,
  AuthenticatedIrmaosIdRoute: AuthenticatedIrmaosIdRoute,
  AuthenticatedIrmaosNovoRoute: AuthenticatedIrmaosNovoRoute,
  AuthenticatedOrgsPotenciasRoute: AuthenticatedOrgsPotenciasRoute,
  AuthenticatedRelatoriosFrequenciaRoute:
    AuthenticatedRelatoriosFrequenciaRoute,
  AuthenticatedRelatoriosInadimplentesRoute:
    AuthenticatedRelatoriosInadimplentesRoute,
  AuthenticatedSessoesIdRoute: AuthenticatedSessoesIdRoute,
  AuthenticatedSgcabCobrancasRoute: AuthenticatedSgcabCobrancasRoute,
  AuthenticatedTesourariaConciliacaoRoute:
    AuthenticatedTesourariaConciliacaoRoute,
  AuthenticatedTesourariaContasRoute: AuthenticatedTesourariaContasRoute,
  AuthenticatedTesourariaContasPagarRoute:
    AuthenticatedTesourariaContasPagarRoute,
  AuthenticatedTesourariaMovimentosRoute:
    AuthenticatedTesourariaMovimentosRoute,
  AuthenticatedTesourariaParametrosRoute:
    AuthenticatedTesourariaParametrosRoute,
  AuthenticatedTesourariaParcelamentosRoute:
    AuthenticatedTesourariaParcelamentosRoute,
  AuthenticatedTesourariaPlanoContasRoute:
    AuthenticatedTesourariaPlanoContasRoute,
  AuthenticatedTesourariaRecibosRoute: AuthenticatedTesourariaRecibosRoute,
  AuthenticatedTesourariaRecorrentesRoute:
    AuthenticatedTesourariaRecorrentesRoute,
  AuthenticatedTesourariaTabelaValoresRoute:
    AuthenticatedTesourariaTabelaValoresRoute,
  AuthenticatedTesourariaTroncoRoute: AuthenticatedTesourariaTroncoRoute,
  AuthenticatedBibliotecaIndexRoute: AuthenticatedBibliotecaIndexRoute,
  AuthenticatedCalendarioIndexRoute: AuthenticatedCalendarioIndexRoute,
  AuthenticatedComissoesIndexRoute: AuthenticatedComissoesIndexRoute,
  AuthenticatedComunicacoesIndexRoute: AuthenticatedComunicacoesIndexRoute,
  AuthenticatedEnquetesIndexRoute: AuthenticatedEnquetesIndexRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
  AuthenticatedGestoesIndexRoute: AuthenticatedGestoesIndexRoute,
  AuthenticatedIntersticoIndexRoute: AuthenticatedIntersticoIndexRoute,
  AuthenticatedIrmaosIndexRoute: AuthenticatedIrmaosIndexRoute,
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
  AuthenticatedSessoesIndexRoute: AuthenticatedSessoesIndexRoute,
  AuthenticatedTerceirosIndexRoute: AuthenticatedTerceirosIndexRoute,
  AuthenticatedTesourariaIndexRoute: AuthenticatedTesourariaIndexRoute,
  AuthenticatedUsuariosIndexRoute: AuthenticatedUsuariosIndexRoute,
  AuthenticatedTesourariaFaturasIdRoute: AuthenticatedTesourariaFaturasIdRoute,
  AuthenticatedTesourariaFaturasIndexRoute:
    AuthenticatedTesourariaFaturasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AceiteTermosRoute: AceiteTermosRoute,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
