/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTesourariaIndexRouteImport } from './routes/_authenticated/tesouraria/index'
import { Route as AuthenticatedTerceirosIndexRouteImport } from './routes/_authenticated/terceiros/index'
import { Route as AuthenticatedSessoesIndexRouteImport } from './routes/_authenticated/sessoes/index'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs/index'
import { Route as AuthenticatedIrmaosIndexRouteImport } from './routes/_authenticated/irmaos/index'
import { Route as AuthenticatedGestoesIndexRouteImport } from './routes/_authenticated/gestoes/index'
import { Route as AuthenticatedTesourariaTroncoRouteImport } from './routes/_authenticated/tesouraria/tronco'
import { Route as AuthenticatedTesourariaRecorrentesRouteImport } from './routes/_authenticated/tesouraria/recorrentes'
import { Route as AuthenticatedTesourariaRecibosRouteImport } from './routes/_authenticated/tesouraria/recibos'
import { Route as AuthenticatedTesourariaPlanoContasRouteImport } from './routes/_authenticated/tesouraria/plano-contas'
import { Route as AuthenticatedTesourariaParcelamentosRouteImport } from './routes/_authenticated/tesouraria/parcelamentos'
import { Route as AuthenticatedTesourariaParametrosRouteImport } from './routes/_authenticated/tesouraria/parametros'
import { Route as AuthenticatedTesourariaMovimentosRouteImport } from './routes/_authenticated/tesouraria/movimentos'
import { Route as AuthenticatedTesourariaFaturasRouteImport } from './routes/_authenticated/tesouraria/faturas'
import { Route as AuthenticatedTesourariaContasPagarRouteImport } from './routes/_authenticated/tesouraria/contas-pagar'
import { Route as AuthenticatedTesourariaContasRouteImport } from './routes/_authenticated/tesouraria/contas'
import { Route as AuthenticatedTesourariaConciliacaoRouteImport } from './routes/_authenticated/tesouraria/conciliacao'
import { Route as AuthenticatedSessoesIdRouteImport } from './routes/_authenticated/sessoes/$id'
import { Route as AuthenticatedRelatoriosInadimplentesRouteImport } from './routes/_authenticated/relatorios/inadimplentes'
import { Route as AuthenticatedRelatoriosFrequenciaRouteImport } from './routes/_authenticated/relatorios/frequencia'
import { Route as AuthenticatedOrgsPotenciasRouteImport } from './routes/_authenticated/orgs/potencias'
import { Route as AuthenticatedIrmaosNovoRouteImport } from './routes/_authenticated/irmaos/novo'
import { Route as AuthenticatedIrmaosIdRouteImport } from './routes/_authenticated/irmaos/$id'
import { Route as AuthenticatedGestoesCargosRouteImport } from './routes/_authenticated/gestoes/cargos'
import { Route as AuthenticatedContabilidadeRazaoRouteImport } from './routes/_authenticated/contabilidade/razao'
import { Route as AuthenticatedContabilidadeOrcamentoRouteImport } from './routes/_authenticated/contabilidade/orcamento'
import { Route as AuthenticatedContabilidadeFluxoCaixaRouteImport } from './routes/_authenticated/contabilidade/fluxo-caixa'
import { Route as AuthenticatedContabilidadeFechamentoRouteImport } from './routes/_authenticated/contabilidade/fechamento'
import { Route as AuthenticatedContabilidadeDreOrcadoRouteImport } from './routes/_authenticated/contabilidade/dre-orcado'
import { Route as AuthenticatedContabilidadeDreRouteImport } from './routes/_authenticated/contabilidade/dre'
import { Route as AuthenticatedContabilidadeDiarioRouteImport } from './routes/_authenticated/contabilidade/diario'
import { Route as AuthenticatedContabilidadeBalanceteRouteImport } from './routes/_authenticated/contabilidade/balancete'
import { Route as AuthenticatedContabilidadeAuditoriaRouteImport } from './routes/_authenticated/contabilidade/auditoria'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTesourariaIndexRoute =
  AuthenticatedTesourariaIndexRouteImport.update({
    id: '/tesouraria/',
    path: '/tesouraria/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerceirosIndexRoute =
  AuthenticatedTerceirosIndexRouteImport.update({
    id: '/terceiros/',
    path: '/terceiros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIndexRoute =
  AuthenticatedSessoesIndexRouteImport.update({
    id: '/sessoes/',
    path: '/sessoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIrmaosIndexRoute =
  AuthenticatedIrmaosIndexRouteImport.update({
    id: '/irmaos/',
    path: '/irmaos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestoesIndexRoute =
  AuthenticatedGestoesIndexRouteImport.update({
    id: '/gestoes/',
    path: '/gestoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaTroncoRoute =
  AuthenticatedTesourariaTroncoRouteImport.update({
    id: '/tesouraria/tronco',
    path: '/tesouraria/tronco',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaRecorrentesRoute =
  AuthenticatedTesourariaRecorrentesRouteImport.update({
    id: '/tesouraria/recorrentes',
    path: '/tesouraria/recorrentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaRecibosRoute =
  AuthenticatedTesourariaRecibosRouteImport.update({
    id: '/tesouraria/recibos',
    path: '/tesouraria/recibos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaPlanoContasRoute =
  AuthenticatedTesourariaPlanoContasRouteImport.update({
    id: '/tesouraria/plano-contas',
    path: '/tesouraria/plano-contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaParcelamentosRoute =
  AuthenticatedTesourariaParcelamentosRouteImport.update({
    id: '/tesouraria/parcelamentos',
    path: '/tesouraria/parcelamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaParametrosRoute =
  AuthenticatedTesourariaParametrosRouteImport.update({
    id: '/tesouraria/parametros',
    path: '/tesouraria/parametros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaMovimentosRoute =
  AuthenticatedTesourariaMovimentosRouteImport.update({
    id: '/tesouraria/movimentos',
    path: '/tesouraria/movimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaFaturasRoute =
  AuthenticatedTesourariaFaturasRouteImport.update({
    id: '/tesouraria/faturas',
    path: '/tesouraria/faturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaContasPagarRoute =
  AuthenticatedTesourariaContasPagarRouteImport.update({
    id: '/tesouraria/contas-pagar',
    path: '/tesouraria/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaContasRoute =
  AuthenticatedTesourariaContasRouteImport.update({
    id: '/tesouraria/contas',
    path: '/tesouraria/contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTesourariaConciliacaoRoute =
  AuthenticatedTesourariaConciliacaoRouteImport.update({
    id: '/tesouraria/conciliacao',
    path: '/tesouraria/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIdRoute = AuthenticatedSessoesIdRouteImport.update({
  id: '/sessoes/$id',
  path: '/sessoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosInadimplentesRoute =
  AuthenticatedRelatoriosInadimplentesRouteImport.update({
    id: '/relatorios/inadimplentes',
    path: '/relatorios/inadimplentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosFrequenciaRoute =
  AuthenticatedRelatoriosFrequenciaRouteImport.update({
    id: '/relatorios/frequencia',
    path: '/relatorios/frequencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsPotenciasRoute =
  AuthenticatedOrgsPotenciasRouteImport.update({
    id: '/orgs/potencias',
    path: '/orgs/potencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIrmaosNovoRoute = AuthenticatedIrmaosNovoRouteImport.update({
  id: '/irmaos/novo',
  path: '/irmaos/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIrmaosIdRoute = AuthenticatedIrmaosIdRouteImport.update({
  id: '/irmaos/$id',
  path: '/irmaos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestoesCargosRoute =
  AuthenticatedGestoesCargosRouteImport.update({
    id: '/gestoes/cargos',
    path: '/gestoes/cargos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeRazaoRoute =
  AuthenticatedContabilidadeRazaoRouteImport.update({
    id: '/contabilidade/razao',
    path: '/contabilidade/razao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeOrcamentoRoute =
  AuthenticatedContabilidadeOrcamentoRouteImport.update({
    id: '/contabilidade/orcamento',
    path: '/contabilidade/orcamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeFluxoCaixaRoute =
  AuthenticatedContabilidadeFluxoCaixaRouteImport.update({
    id: '/contabilidade/fluxo-caixa',
    path: '/contabilidade/fluxo-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeFechamentoRoute =
  AuthenticatedContabilidadeFechamentoRouteImport.update({
    id: '/contabilidade/fechamento',
    path: '/contabilidade/fechamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeDreOrcadoRoute =
  AuthenticatedContabilidadeDreOrcadoRouteImport.update({
    id: '/contabilidade/dre-orcado',
    path: '/contabilidade/dre-orcado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeDreRoute =
  AuthenticatedContabilidadeDreRouteImport.update({
    id: '/contabilidade/dre',
    path: '/contabilidade/dre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeDiarioRoute =
  AuthenticatedContabilidadeDiarioRouteImport.update({
    id: '/contabilidade/diario',
    path: '/contabilidade/diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeBalanceteRoute =
  AuthenticatedContabilidadeBalanceteRouteImport.update({
    id: '/contabilidade/balancete',
    path: '/contabilidade/balancete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeAuditoriaRoute =
  AuthenticatedContabilidadeAuditoriaRouteImport.update({
    id: '/contabilidade/auditoria',
    path: '/contabilidade/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/contabilidade/balancete': typeof AuthenticatedContabilidadeBalanceteRoute
  '/contabilidade/diario': typeof AuthenticatedContabilidadeDiarioRoute
  '/contabilidade/dre': typeof AuthenticatedContabilidadeDreRoute
  '/contabilidade/dre-orcado': typeof AuthenticatedContabilidadeDreOrcadoRoute
  '/contabilidade/fechamento': typeof AuthenticatedContabilidadeFechamentoRoute
  '/contabilidade/fluxo-caixa': typeof AuthenticatedContabilidadeFluxoCaixaRoute
  '/contabilidade/orcamento': typeof AuthenticatedContabilidadeOrcamentoRoute
  '/contabilidade/razao': typeof AuthenticatedContabilidadeRazaoRoute
  '/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/tesouraria/conciliacao': typeof AuthenticatedTesourariaConciliacaoRoute
  '/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/tesouraria/faturas': typeof AuthenticatedTesourariaFaturasRoute
  '/tesouraria/movimentos': typeof AuthenticatedTesourariaMovimentosRoute
  '/tesouraria/parametros': typeof AuthenticatedTesourariaParametrosRoute
  '/tesouraria/parcelamentos': typeof AuthenticatedTesourariaParcelamentosRoute
  '/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/tesouraria/recibos': typeof AuthenticatedTesourariaRecibosRoute
  '/tesouraria/recorrentes': typeof AuthenticatedTesourariaRecorrentesRoute
  '/tesouraria/tronco': typeof AuthenticatedTesourariaTroncoRoute
  '/gestoes/': typeof AuthenticatedGestoesIndexRoute
  '/irmaos/': typeof AuthenticatedIrmaosIndexRoute
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/terceiros/': typeof AuthenticatedTerceirosIndexRoute
  '/tesouraria/': typeof AuthenticatedTesourariaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/contabilidade/balancete': typeof AuthenticatedContabilidadeBalanceteRoute
  '/contabilidade/diario': typeof AuthenticatedContabilidadeDiarioRoute
  '/contabilidade/dre': typeof AuthenticatedContabilidadeDreRoute
  '/contabilidade/dre-orcado': typeof AuthenticatedContabilidadeDreOrcadoRoute
  '/contabilidade/fechamento': typeof AuthenticatedContabilidadeFechamentoRoute
  '/contabilidade/fluxo-caixa': typeof AuthenticatedContabilidadeFluxoCaixaRoute
  '/contabilidade/orcamento': typeof AuthenticatedContabilidadeOrcamentoRoute
  '/contabilidade/razao': typeof AuthenticatedContabilidadeRazaoRoute
  '/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/tesouraria/conciliacao': typeof AuthenticatedTesourariaConciliacaoRoute
  '/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/tesouraria/faturas': typeof AuthenticatedTesourariaFaturasRoute
  '/tesouraria/movimentos': typeof AuthenticatedTesourariaMovimentosRoute
  '/tesouraria/parametros': typeof AuthenticatedTesourariaParametrosRoute
  '/tesouraria/parcelamentos': typeof AuthenticatedTesourariaParcelamentosRoute
  '/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/tesouraria/recibos': typeof AuthenticatedTesourariaRecibosRoute
  '/tesouraria/recorrentes': typeof AuthenticatedTesourariaRecorrentesRoute
  '/tesouraria/tronco': typeof AuthenticatedTesourariaTroncoRoute
  '/gestoes': typeof AuthenticatedGestoesIndexRoute
  '/irmaos': typeof AuthenticatedIrmaosIndexRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/sessoes': typeof AuthenticatedSessoesIndexRoute
  '/terceiros': typeof AuthenticatedTerceirosIndexRoute
  '/tesouraria': typeof AuthenticatedTesourariaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/contabilidade/auditoria': typeof AuthenticatedContabilidadeAuditoriaRoute
  '/_authenticated/contabilidade/balancete': typeof AuthenticatedContabilidadeBalanceteRoute
  '/_authenticated/contabilidade/diario': typeof AuthenticatedContabilidadeDiarioRoute
  '/_authenticated/contabilidade/dre': typeof AuthenticatedContabilidadeDreRoute
  '/_authenticated/contabilidade/dre-orcado': typeof AuthenticatedContabilidadeDreOrcadoRoute
  '/_authenticated/contabilidade/fechamento': typeof AuthenticatedContabilidadeFechamentoRoute
  '/_authenticated/contabilidade/fluxo-caixa': typeof AuthenticatedContabilidadeFluxoCaixaRoute
  '/_authenticated/contabilidade/orcamento': typeof AuthenticatedContabilidadeOrcamentoRoute
  '/_authenticated/contabilidade/razao': typeof AuthenticatedContabilidadeRazaoRoute
  '/_authenticated/gestoes/cargos': typeof AuthenticatedGestoesCargosRoute
  '/_authenticated/irmaos/$id': typeof AuthenticatedIrmaosIdRoute
  '/_authenticated/irmaos/novo': typeof AuthenticatedIrmaosNovoRoute
  '/_authenticated/orgs/potencias': typeof AuthenticatedOrgsPotenciasRoute
  '/_authenticated/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/_authenticated/relatorios/inadimplentes': typeof AuthenticatedRelatoriosInadimplentesRoute
  '/_authenticated/sessoes/$id': typeof AuthenticatedSessoesIdRoute
  '/_authenticated/tesouraria/conciliacao': typeof AuthenticatedTesourariaConciliacaoRoute
  '/_authenticated/tesouraria/contas': typeof AuthenticatedTesourariaContasRoute
  '/_authenticated/tesouraria/contas-pagar': typeof AuthenticatedTesourariaContasPagarRoute
  '/_authenticated/tesouraria/faturas': typeof AuthenticatedTesourariaFaturasRoute
  '/_authenticated/tesouraria/movimentos': typeof AuthenticatedTesourariaMovimentosRoute
  '/_authenticated/tesouraria/parametros': typeof AuthenticatedTesourariaParametrosRoute
  '/_authenticated/tesouraria/parcelamentos': typeof AuthenticatedTesourariaParcelamentosRoute
  '/_authenticated/tesouraria/plano-contas': typeof AuthenticatedTesourariaPlanoContasRoute
  '/_authenticated/tesouraria/recibos': typeof AuthenticatedTesourariaRecibosRoute
  '/_authenticated/tesouraria/recorrentes': typeof AuthenticatedTesourariaRecorrentesRoute
  '/_authenticated/tesouraria/tronco': typeof AuthenticatedTesourariaTroncoRoute
  '/_authenticated/gestoes/': typeof AuthenticatedGestoesIndexRoute
  '/_authenticated/irmaos/': typeof AuthenticatedIrmaosIndexRoute
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/_authenticated/terceiros/': typeof AuthenticatedTerceirosIndexRoute
  '/_authenticated/tesouraria/': typeof AuthenticatedTesourariaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/painel'
    | '/contabilidade/auditoria'
    | '/contabilidade/balancete'
    | '/contabilidade/diario'
    | '/contabilidade/dre'
    | '/contabilidade/dre-orcado'
    | '/contabilidade/fechamento'
    | '/contabilidade/fluxo-caixa'
    | '/contabilidade/orcamento'
    | '/contabilidade/razao'
    | '/gestoes/cargos'
    | '/irmaos/$id'
    | '/irmaos/novo'
    | '/orgs/potencias'
    | '/relatorios/frequencia'
    | '/relatorios/inadimplentes'
    | '/sessoes/$id'
    | '/tesouraria/conciliacao'
    | '/tesouraria/contas'
    | '/tesouraria/contas-pagar'
    | '/tesouraria/faturas'
    | '/tesouraria/movimentos'
    | '/tesouraria/parametros'
    | '/tesouraria/parcelamentos'
    | '/tesouraria/plano-contas'
    | '/tesouraria/recibos'
    | '/tesouraria/recorrentes'
    | '/tesouraria/tronco'
    | '/gestoes/'
    | '/irmaos/'
    | '/orgs/'
    | '/sessoes/'
    | '/terceiros/'
    | '/tesouraria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/painel'
    | '/contabilidade/auditoria'
    | '/contabilidade/balancete'
    | '/contabilidade/diario'
    | '/contabilidade/dre'
    | '/contabilidade/dre-orcado'
    | '/contabilidade/fechamento'
    | '/contabilidade/fluxo-caixa'
    | '/contabilidade/orcamento'
    | '/contabilidade/razao'
    | '/gestoes/cargos'
    | '/irmaos/$id'
    | '/irmaos/novo'
    | '/orgs/potencias'
    | '/relatorios/frequencia'
    | '/relatorios/inadimplentes'
    | '/sessoes/$id'
    | '/tesouraria/conciliacao'
    | '/tesouraria/contas'
    | '/tesouraria/contas-pagar'
    | '/tesouraria/faturas'
    | '/tesouraria/movimentos'
    | '/tesouraria/parametros'
    | '/tesouraria/parcelamentos'
    | '/tesouraria/plano-contas'
    | '/tesouraria/recibos'
    | '/tesouraria/recorrentes'
    | '/tesouraria/tronco'
    | '/gestoes'
    | '/irmaos'
    | '/orgs'
    | '/sessoes'
    | '/terceiros'
    | '/tesouraria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/painel'
    | '/_authenticated/contabilidade/auditoria'
    | '/_authenticated/contabilidade/balancete'
    | '/_authenticated/contabilidade/diario'
    | '/_authenticated/contabilidade/dre'
    | '/_authenticated/contabilidade/dre-orcado'
    | '/_authenticated/contabilidade/fechamento'
    | '/_authenticated/contabilidade/fluxo-caixa'
    | '/_authenticated/contabilidade/orcamento'
    | '/_authenticated/contabilidade/razao'
    | '/_authenticated/gestoes/cargos'
    | '/_authenticated/irmaos/$id'
    | '/_authenticated/irmaos/novo'
    | '/_authenticated/orgs/potencias'
    | '/_authenticated/relatorios/frequencia'
    | '/_authenticated/relatorios/inadimplentes'
    | '/_authenticated/sessoes/$id'
    | '/_authenticated/tesouraria/conciliacao'
    | '/_authenticated/tesouraria/contas'
    | '/_authenticated/tesouraria/contas-pagar'
    | '/_authenticated/tesouraria/faturas'
    | '/_authenticated/tesouraria/movimentos'
    | '/_authenticated/tesouraria/parametros'
    | '/_authenticated/tesouraria/parcelamentos'
    | '/_authenticated/tesouraria/plano-contas'
    | '/_authenticated/tesouraria/recibos'
    | '/_authenticated/tesouraria/recorrentes'
    | '/_authenticated/tesouraria/tronco'
    | '/_authenticated/gestoes/'
    | '/_authenticated/irmaos/'
    | '/_authenticated/orgs/'
    | '/_authenticated/sessoes/'
    | '/_authenticated/terceiros/'
    | '/_authenticated/tesouraria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/': {
      id: '/_authenticated/tesouraria/'
      path: '/tesouraria'
      fullPath: '/tesouraria/'
      preLoaderRoute: typeof AuthenticatedTesourariaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terceiros/': {
      id: '/_authenticated/terceiros/'
      path: '/terceiros'
      fullPath: '/terceiros/'
      preLoaderRoute: typeof AuthenticatedTerceirosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/': {
      id: '/_authenticated/sessoes/'
      path: '/sessoes'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof AuthenticatedSessoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/': {
      id: '/_authenticated/irmaos/'
      path: '/irmaos'
      fullPath: '/irmaos/'
      preLoaderRoute: typeof AuthenticatedIrmaosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestoes/': {
      id: '/_authenticated/gestoes/'
      path: '/gestoes'
      fullPath: '/gestoes/'
      preLoaderRoute: typeof AuthenticatedGestoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/tronco': {
      id: '/_authenticated/tesouraria/tronco'
      path: '/tesouraria/tronco'
      fullPath: '/tesouraria/tronco'
      preLoaderRoute: typeof AuthenticatedTesourariaTroncoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/recorrentes': {
      id: '/_authenticated/tesouraria/recorrentes'
      path: '/tesouraria/recorrentes'
      fullPath: '/tesouraria/recorrentes'
      preLoaderRoute: typeof AuthenticatedTesourariaRecorrentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/recibos': {
      id: '/_authenticated/tesouraria/recibos'
      path: '/tesouraria/recibos'
      fullPath: '/tesouraria/recibos'
      preLoaderRoute: typeof AuthenticatedTesourariaRecibosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/plano-contas': {
      id: '/_authenticated/tesouraria/plano-contas'
      path: '/tesouraria/plano-contas'
      fullPath: '/tesouraria/plano-contas'
      preLoaderRoute: typeof AuthenticatedTesourariaPlanoContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/parcelamentos': {
      id: '/_authenticated/tesouraria/parcelamentos'
      path: '/tesouraria/parcelamentos'
      fullPath: '/tesouraria/parcelamentos'
      preLoaderRoute: typeof AuthenticatedTesourariaParcelamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/parametros': {
      id: '/_authenticated/tesouraria/parametros'
      path: '/tesouraria/parametros'
      fullPath: '/tesouraria/parametros'
      preLoaderRoute: typeof AuthenticatedTesourariaParametrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/movimentos': {
      id: '/_authenticated/tesouraria/movimentos'
      path: '/tesouraria/movimentos'
      fullPath: '/tesouraria/movimentos'
      preLoaderRoute: typeof AuthenticatedTesourariaMovimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/faturas': {
      id: '/_authenticated/tesouraria/faturas'
      path: '/tesouraria/faturas'
      fullPath: '/tesouraria/faturas'
      preLoaderRoute: typeof AuthenticatedTesourariaFaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/contas-pagar': {
      id: '/_authenticated/tesouraria/contas-pagar'
      path: '/tesouraria/contas-pagar'
      fullPath: '/tesouraria/contas-pagar'
      preLoaderRoute: typeof AuthenticatedTesourariaContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/contas': {
      id: '/_authenticated/tesouraria/contas'
      path: '/tesouraria/contas'
      fullPath: '/tesouraria/contas'
      preLoaderRoute: typeof AuthenticatedTesourariaContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tesouraria/conciliacao': {
      id: '/_authenticated/tesouraria/conciliacao'
      path: '/tesouraria/conciliacao'
      fullPath: '/tesouraria/conciliacao'
      preLoaderRoute: typeof AuthenticatedTesourariaConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/$id': {
      id: '/_authenticated/sessoes/$id'
      path: '/sessoes/$id'
      fullPath: '/sessoes/$id'
      preLoaderRoute: typeof AuthenticatedSessoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/inadimplentes': {
      id: '/_authenticated/relatorios/inadimplentes'
      path: '/relatorios/inadimplentes'
      fullPath: '/relatorios/inadimplentes'
      preLoaderRoute: typeof AuthenticatedRelatoriosInadimplentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/frequencia': {
      id: '/_authenticated/relatorios/frequencia'
      path: '/relatorios/frequencia'
      fullPath: '/relatorios/frequencia'
      preLoaderRoute: typeof AuthenticatedRelatoriosFrequenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/potencias': {
      id: '/_authenticated/orgs/potencias'
      path: '/orgs/potencias'
      fullPath: '/orgs/potencias'
      preLoaderRoute: typeof AuthenticatedOrgsPotenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/novo': {
      id: '/_authenticated/irmaos/novo'
      path: '/irmaos/novo'
      fullPath: '/irmaos/novo'
      preLoaderRoute: typeof AuthenticatedIrmaosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irmaos/$id': {
      id: '/_authenticated/irmaos/$id'
      path: '/irmaos/$id'
      fullPath: '/irmaos/$id'
      preLoaderRoute: typeof AuthenticatedIrmaosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestoes/cargos': {
      id: '/_authenticated/gestoes/cargos'
      path: '/gestoes/cargos'
      fullPath: '/gestoes/cargos'
      preLoaderRoute: typeof AuthenticatedGestoesCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/razao': {
      id: '/_authenticated/contabilidade/razao'
      path: '/contabilidade/razao'
      fullPath: '/contabilidade/razao'
      preLoaderRoute: typeof AuthenticatedContabilidadeRazaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/orcamento': {
      id: '/_authenticated/contabilidade/orcamento'
      path: '/contabilidade/orcamento'
      fullPath: '/contabilidade/orcamento'
      preLoaderRoute: typeof AuthenticatedContabilidadeOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/fluxo-caixa': {
      id: '/_authenticated/contabilidade/fluxo-caixa'
      path: '/contabilidade/fluxo-caixa'
      fullPath: '/contabilidade/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedContabilidadeFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/fechamento': {
      id: '/_authenticated/contabilidade/fechamento'
      path: '/contabilidade/fechamento'
      fullPath: '/contabilidade/fechamento'
      preLoaderRoute: typeof AuthenticatedContabilidadeFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/dre-orcado': {
      id: '/_authenticated/contabilidade/dre-orcado'
      path: '/contabilidade/dre-orcado'
      fullPath: '/contabilidade/dre-orcado'
      preLoaderRoute: typeof AuthenticatedContabilidadeDreOrcadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/dre': {
      id: '/_authenticated/contabilidade/dre'
      path: '/contabilidade/dre'
      fullPath: '/contabilidade/dre'
      preLoaderRoute: typeof AuthenticatedContabilidadeDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/diario': {
      id: '/_authenticated/contabilidade/diario'
      path: '/contabilidade/diario'
      fullPath: '/contabilidade/diario'
      preLoaderRoute: typeof AuthenticatedContabilidadeDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/balancete': {
      id: '/_authenticated/contabilidade/balancete'
      path: '/contabilidade/balancete'
      fullPath: '/contabilidade/balancete'
      preLoaderRoute: typeof AuthenticatedContabilidadeBalanceteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/auditoria': {
      id: '/_authenticated/contabilidade/auditoria'
      path: '/contabilidade/auditoria'
      fullPath: '/contabilidade/auditoria'
      preLoaderRoute: typeof AuthenticatedContabilidadeAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedContabilidadeAuditoriaRoute: typeof AuthenticatedContabilidadeAuditoriaRoute
  AuthenticatedContabilidadeBalanceteRoute: typeof AuthenticatedContabilidadeBalanceteRoute
  AuthenticatedContabilidadeDiarioRoute: typeof AuthenticatedContabilidadeDiarioRoute
  AuthenticatedContabilidadeDreRoute: typeof AuthenticatedContabilidadeDreRoute
  AuthenticatedContabilidadeDreOrcadoRoute: typeof AuthenticatedContabilidadeDreOrcadoRoute
  AuthenticatedContabilidadeFechamentoRoute: typeof AuthenticatedContabilidadeFechamentoRoute
  AuthenticatedContabilidadeFluxoCaixaRoute: typeof AuthenticatedContabilidadeFluxoCaixaRoute
  AuthenticatedContabilidadeOrcamentoRoute: typeof AuthenticatedContabilidadeOrcamentoRoute
  AuthenticatedContabilidadeRazaoRoute: typeof AuthenticatedContabilidadeRazaoRoute
  AuthenticatedGestoesCargosRoute: typeof AuthenticatedGestoesCargosRoute
  AuthenticatedIrmaosIdRoute: typeof AuthenticatedIrmaosIdRoute
  AuthenticatedIrmaosNovoRoute: typeof AuthenticatedIrmaosNovoRoute
  AuthenticatedOrgsPotenciasRoute: typeof AuthenticatedOrgsPotenciasRoute
  AuthenticatedRelatoriosFrequenciaRoute: typeof AuthenticatedRelatoriosFrequenciaRoute
  AuthenticatedRelatoriosInadimplentesRoute: typeof AuthenticatedRelatoriosInadimplentesRoute
  AuthenticatedSessoesIdRoute: typeof AuthenticatedSessoesIdRoute
  AuthenticatedTesourariaConciliacaoRoute: typeof AuthenticatedTesourariaConciliacaoRoute
  AuthenticatedTesourariaContasRoute: typeof AuthenticatedTesourariaContasRoute
  AuthenticatedTesourariaContasPagarRoute: typeof AuthenticatedTesourariaContasPagarRoute
  AuthenticatedTesourariaFaturasRoute: typeof AuthenticatedTesourariaFaturasRoute
  AuthenticatedTesourariaMovimentosRoute: typeof AuthenticatedTesourariaMovimentosRoute
  AuthenticatedTesourariaParametrosRoute: typeof AuthenticatedTesourariaParametrosRoute
  AuthenticatedTesourariaParcelamentosRoute: typeof AuthenticatedTesourariaParcelamentosRoute
  AuthenticatedTesourariaPlanoContasRoute: typeof AuthenticatedTesourariaPlanoContasRoute
  AuthenticatedTesourariaRecibosRoute: typeof AuthenticatedTesourariaRecibosRoute
  AuthenticatedTesourariaRecorrentesRoute: typeof AuthenticatedTesourariaRecorrentesRoute
  AuthenticatedTesourariaTroncoRoute: typeof AuthenticatedTesourariaTroncoRoute
  AuthenticatedGestoesIndexRoute: typeof AuthenticatedGestoesIndexRoute
  AuthenticatedIrmaosIndexRoute: typeof AuthenticatedIrmaosIndexRoute
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
  AuthenticatedSessoesIndexRoute: typeof AuthenticatedSessoesIndexRoute
  AuthenticatedTerceirosIndexRoute: typeof AuthenticatedTerceirosIndexRoute
  AuthenticatedTesourariaIndexRoute: typeof AuthenticatedTesourariaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedContabilidadeAuditoriaRoute:
    AuthenticatedContabilidadeAuditoriaRoute,
  AuthenticatedContabilidadeBalanceteRoute:
    AuthenticatedContabilidadeBalanceteRoute,
  AuthenticatedContabilidadeDiarioRoute: AuthenticatedContabilidadeDiarioRoute,
  AuthenticatedContabilidadeDreRoute: AuthenticatedContabilidadeDreRoute,
  AuthenticatedContabilidadeDreOrcadoRoute:
    AuthenticatedContabilidadeDreOrcadoRoute,
  AuthenticatedContabilidadeFechamentoRoute:
    AuthenticatedContabilidadeFechamentoRoute,
  AuthenticatedContabilidadeFluxoCaixaRoute:
    AuthenticatedContabilidadeFluxoCaixaRoute,
  AuthenticatedContabilidadeOrcamentoRoute:
    AuthenticatedContabilidadeOrcamentoRoute,
  AuthenticatedContabilidadeRazaoRoute: AuthenticatedContabilidadeRazaoRoute,
  AuthenticatedGestoesCargosRoute: AuthenticatedGestoesCargosRoute,
  AuthenticatedIrmaosIdRoute: AuthenticatedIrmaosIdRoute,
  AuthenticatedIrmaosNovoRoute: AuthenticatedIrmaosNovoRoute,
  AuthenticatedOrgsPotenciasRoute: AuthenticatedOrgsPotenciasRoute,
  AuthenticatedRelatoriosFrequenciaRoute:
    AuthenticatedRelatoriosFrequenciaRoute,
  AuthenticatedRelatoriosInadimplentesRoute:
    AuthenticatedRelatoriosInadimplentesRoute,
  AuthenticatedSessoesIdRoute: AuthenticatedSessoesIdRoute,
  AuthenticatedTesourariaConciliacaoRoute:
    AuthenticatedTesourariaConciliacaoRoute,
  AuthenticatedTesourariaContasRoute: AuthenticatedTesourariaContasRoute,
  AuthenticatedTesourariaContasPagarRoute:
    AuthenticatedTesourariaContasPagarRoute,
  AuthenticatedTesourariaFaturasRoute: AuthenticatedTesourariaFaturasRoute,
  AuthenticatedTesourariaMovimentosRoute:
    AuthenticatedTesourariaMovimentosRoute,
  AuthenticatedTesourariaParametrosRoute:
    AuthenticatedTesourariaParametrosRoute,
  AuthenticatedTesourariaParcelamentosRoute:
    AuthenticatedTesourariaParcelamentosRoute,
  AuthenticatedTesourariaPlanoContasRoute:
    AuthenticatedTesourariaPlanoContasRoute,
  AuthenticatedTesourariaRecibosRoute: AuthenticatedTesourariaRecibosRoute,
  AuthenticatedTesourariaRecorrentesRoute:
    AuthenticatedTesourariaRecorrentesRoute,
  AuthenticatedTesourariaTroncoRoute: AuthenticatedTesourariaTroncoRoute,
  AuthenticatedGestoesIndexRoute: AuthenticatedGestoesIndexRoute,
  AuthenticatedIrmaosIndexRoute: AuthenticatedIrmaosIndexRoute,
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
  AuthenticatedSessoesIndexRoute: AuthenticatedSessoesIndexRoute,
  AuthenticatedTerceirosIndexRoute: AuthenticatedTerceirosIndexRoute,
  AuthenticatedTesourariaIndexRoute: AuthenticatedTesourariaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
